package com.mincrm.entity.model;

import java.util.Date;

public class CrmCustomer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.tenant_id
     *
     * @mbg.generated
     */
    private Integer tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.owner_uid
     *
     * @mbg.generated
     */
    private Integer ownerUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.customer_tel
     *
     * @mbg.generated
     */
    private String customerTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.customer_name
     *
     * @mbg.generated
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.customer_type
     *
     * @mbg.generated
     */
    private String customerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.expiration_time
     *
     * @mbg.generated
     */
    private Date expirationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.active_flag
     *
     * @mbg.generated
     */
    private Boolean activeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.create_uid
     *
     * @mbg.generated
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.update_uid
     *
     * @mbg.generated
     */
    private Integer updateUid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.id
     *
     * @return the value of crm_customer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.id
     *
     * @param id the value for crm_customer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.tenant_id
     *
     * @return the value of crm_customer.tenant_id
     *
     * @mbg.generated
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.tenant_id
     *
     * @param tenantId the value for crm_customer.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.owner_uid
     *
     * @return the value of crm_customer.owner_uid
     *
     * @mbg.generated
     */
    public Integer getOwnerUid() {
        return ownerUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.owner_uid
     *
     * @param ownerUid the value for crm_customer.owner_uid
     *
     * @mbg.generated
     */
    public void setOwnerUid(Integer ownerUid) {
        this.ownerUid = ownerUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.customer_tel
     *
     * @return the value of crm_customer.customer_tel
     *
     * @mbg.generated
     */
    public String getCustomerTel() {
        return customerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.customer_tel
     *
     * @param customerTel the value for crm_customer.customer_tel
     *
     * @mbg.generated
     */
    public void setCustomerTel(String customerTel) {
        this.customerTel = customerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.customer_name
     *
     * @return the value of crm_customer.customer_name
     *
     * @mbg.generated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.customer_name
     *
     * @param customerName the value for crm_customer.customer_name
     *
     * @mbg.generated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.customer_type
     *
     * @return the value of crm_customer.customer_type
     *
     * @mbg.generated
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.customer_type
     *
     * @param customerType the value for crm_customer.customer_type
     *
     * @mbg.generated
     */
    public void setCustomerType(String customerType) {
        this.customerType = customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.expiration_time
     *
     * @return the value of crm_customer.expiration_time
     *
     * @mbg.generated
     */
    public Date getExpirationTime() {
        return expirationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.expiration_time
     *
     * @param expirationTime the value for crm_customer.expiration_time
     *
     * @mbg.generated
     */
    public void setExpirationTime(Date expirationTime) {
        this.expirationTime = expirationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.remark
     *
     * @return the value of crm_customer.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.remark
     *
     * @param remark the value for crm_customer.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.active_flag
     *
     * @return the value of crm_customer.active_flag
     *
     * @mbg.generated
     */
    public Boolean getActiveFlag() {
        return activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.active_flag
     *
     * @param activeFlag the value for crm_customer.active_flag
     *
     * @mbg.generated
     */
    public void setActiveFlag(Boolean activeFlag) {
        this.activeFlag = activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.create_date
     *
     * @return the value of crm_customer.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.create_date
     *
     * @param createDate the value for crm_customer.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.create_uid
     *
     * @return the value of crm_customer.create_uid
     *
     * @mbg.generated
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.create_uid
     *
     * @param createUid the value for crm_customer.create_uid
     *
     * @mbg.generated
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.update_date
     *
     * @return the value of crm_customer.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.update_date
     *
     * @param updateDate the value for crm_customer.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.update_uid
     *
     * @return the value of crm_customer.update_uid
     *
     * @mbg.generated
     */
    public Integer getUpdateUid() {
        return updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.update_uid
     *
     * @param updateUid the value for crm_customer.update_uid
     *
     * @mbg.generated
     */
    public void setUpdateUid(Integer updateUid) {
        this.updateUid = updateUid;
    }
}