package com.mincrm.entity.model;

import java.util.Date;

public class CrmTenant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_tenant.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_tenant.tenant_name
     *
     * @mbg.generated
     */
    private String tenantName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_tenant.tenant_tel
     *
     * @mbg.generated
     */
    private String tenantTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_tenant.tenant_email
     *
     * @mbg.generated
     */
    private String tenantEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_tenant.tenant_address
     *
     * @mbg.generated
     */
    private String tenantAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_tenant.active_flag
     *
     * @mbg.generated
     */
    private Boolean activeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_tenant.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_tenant.create_uid
     *
     * @mbg.generated
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_tenant.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_tenant.update_uid
     *
     * @mbg.generated
     */
    private Integer updateUid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_tenant.id
     *
     * @return the value of crm_tenant.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_tenant.id
     *
     * @param id the value for crm_tenant.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_tenant.tenant_name
     *
     * @return the value of crm_tenant.tenant_name
     *
     * @mbg.generated
     */
    public String getTenantName() {
        return tenantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_tenant.tenant_name
     *
     * @param tenantName the value for crm_tenant.tenant_name
     *
     * @mbg.generated
     */
    public void setTenantName(String tenantName) {
        this.tenantName = tenantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_tenant.tenant_tel
     *
     * @return the value of crm_tenant.tenant_tel
     *
     * @mbg.generated
     */
    public String getTenantTel() {
        return tenantTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_tenant.tenant_tel
     *
     * @param tenantTel the value for crm_tenant.tenant_tel
     *
     * @mbg.generated
     */
    public void setTenantTel(String tenantTel) {
        this.tenantTel = tenantTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_tenant.tenant_email
     *
     * @return the value of crm_tenant.tenant_email
     *
     * @mbg.generated
     */
    public String getTenantEmail() {
        return tenantEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_tenant.tenant_email
     *
     * @param tenantEmail the value for crm_tenant.tenant_email
     *
     * @mbg.generated
     */
    public void setTenantEmail(String tenantEmail) {
        this.tenantEmail = tenantEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_tenant.tenant_address
     *
     * @return the value of crm_tenant.tenant_address
     *
     * @mbg.generated
     */
    public String getTenantAddress() {
        return tenantAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_tenant.tenant_address
     *
     * @param tenantAddress the value for crm_tenant.tenant_address
     *
     * @mbg.generated
     */
    public void setTenantAddress(String tenantAddress) {
        this.tenantAddress = tenantAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_tenant.active_flag
     *
     * @return the value of crm_tenant.active_flag
     *
     * @mbg.generated
     */
    public Boolean getActiveFlag() {
        return activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_tenant.active_flag
     *
     * @param activeFlag the value for crm_tenant.active_flag
     *
     * @mbg.generated
     */
    public void setActiveFlag(Boolean activeFlag) {
        this.activeFlag = activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_tenant.create_date
     *
     * @return the value of crm_tenant.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_tenant.create_date
     *
     * @param createDate the value for crm_tenant.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_tenant.create_uid
     *
     * @return the value of crm_tenant.create_uid
     *
     * @mbg.generated
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_tenant.create_uid
     *
     * @param createUid the value for crm_tenant.create_uid
     *
     * @mbg.generated
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_tenant.update_date
     *
     * @return the value of crm_tenant.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_tenant.update_date
     *
     * @param updateDate the value for crm_tenant.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_tenant.update_uid
     *
     * @return the value of crm_tenant.update_uid
     *
     * @mbg.generated
     */
    public Integer getUpdateUid() {
        return updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_tenant.update_uid
     *
     * @param updateUid the value for crm_tenant.update_uid
     *
     * @mbg.generated
     */
    public void setUpdateUid(Integer updateUid) {
        this.updateUid = updateUid;
    }
}