package com.mincrm.entity.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class MbCustomerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    public MbCustomerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andCustomerIdIsNull() {
            addCriterion("customer_id is null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNotNull() {
            addCriterion("customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdEqualTo(Integer value) {
            addCriterion("customer_id =", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotEqualTo(Integer value) {
            addCriterion("customer_id <>", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThan(Integer value) {
            addCriterion("customer_id >", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("customer_id >=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThan(Integer value) {
            addCriterion("customer_id <", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThanOrEqualTo(Integer value) {
            addCriterion("customer_id <=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIn(List<Integer> values) {
            addCriterion("customer_id in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotIn(List<Integer> values) {
            addCriterion("customer_id not in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdBetween(Integer value1, Integer value2) {
            addCriterion("customer_id between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("customer_id not between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerTelIsNull() {
            addCriterion("customer_tel is null");
            return (Criteria) this;
        }

        public Criteria andCustomerTelIsNotNull() {
            addCriterion("customer_tel is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerTelEqualTo(String value) {
            addCriterion("customer_tel =", value, "customerTel");
            return (Criteria) this;
        }

        public Criteria andCustomerTelNotEqualTo(String value) {
            addCriterion("customer_tel <>", value, "customerTel");
            return (Criteria) this;
        }

        public Criteria andCustomerTelGreaterThan(String value) {
            addCriterion("customer_tel >", value, "customerTel");
            return (Criteria) this;
        }

        public Criteria andCustomerTelGreaterThanOrEqualTo(String value) {
            addCriterion("customer_tel >=", value, "customerTel");
            return (Criteria) this;
        }

        public Criteria andCustomerTelLessThan(String value) {
            addCriterion("customer_tel <", value, "customerTel");
            return (Criteria) this;
        }

        public Criteria andCustomerTelLessThanOrEqualTo(String value) {
            addCriterion("customer_tel <=", value, "customerTel");
            return (Criteria) this;
        }

        public Criteria andCustomerTelLike(String value) {
            addCriterion("customer_tel like", value, "customerTel");
            return (Criteria) this;
        }

        public Criteria andCustomerTelNotLike(String value) {
            addCriterion("customer_tel not like", value, "customerTel");
            return (Criteria) this;
        }

        public Criteria andCustomerTelIn(List<String> values) {
            addCriterion("customer_tel in", values, "customerTel");
            return (Criteria) this;
        }

        public Criteria andCustomerTelNotIn(List<String> values) {
            addCriterion("customer_tel not in", values, "customerTel");
            return (Criteria) this;
        }

        public Criteria andCustomerTelBetween(String value1, String value2) {
            addCriterion("customer_tel between", value1, value2, "customerTel");
            return (Criteria) this;
        }

        public Criteria andCustomerTelNotBetween(String value1, String value2) {
            addCriterion("customer_tel not between", value1, value2, "customerTel");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIsNull() {
            addCriterion("customer_name is null");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIsNotNull() {
            addCriterion("customer_name is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerNameEqualTo(String value) {
            addCriterion("customer_name =", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotEqualTo(String value) {
            addCriterion("customer_name <>", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameGreaterThan(String value) {
            addCriterion("customer_name >", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameGreaterThanOrEqualTo(String value) {
            addCriterion("customer_name >=", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLessThan(String value) {
            addCriterion("customer_name <", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLessThanOrEqualTo(String value) {
            addCriterion("customer_name <=", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLike(String value) {
            addCriterion("customer_name like", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotLike(String value) {
            addCriterion("customer_name not like", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIn(List<String> values) {
            addCriterion("customer_name in", values, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotIn(List<String> values) {
            addCriterion("customer_name not in", values, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameBetween(String value1, String value2) {
            addCriterion("customer_name between", value1, value2, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotBetween(String value1, String value2) {
            addCriterion("customer_name not between", value1, value2, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerBirthdayIsNull() {
            addCriterion("customer_birthday is null");
            return (Criteria) this;
        }

        public Criteria andCustomerBirthdayIsNotNull() {
            addCriterion("customer_birthday is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerBirthdayEqualTo(Date value) {
            addCriterionForJDBCDate("customer_birthday =", value, "customerBirthday");
            return (Criteria) this;
        }

        public Criteria andCustomerBirthdayNotEqualTo(Date value) {
            addCriterionForJDBCDate("customer_birthday <>", value, "customerBirthday");
            return (Criteria) this;
        }

        public Criteria andCustomerBirthdayGreaterThan(Date value) {
            addCriterionForJDBCDate("customer_birthday >", value, "customerBirthday");
            return (Criteria) this;
        }

        public Criteria andCustomerBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("customer_birthday >=", value, "customerBirthday");
            return (Criteria) this;
        }

        public Criteria andCustomerBirthdayLessThan(Date value) {
            addCriterionForJDBCDate("customer_birthday <", value, "customerBirthday");
            return (Criteria) this;
        }

        public Criteria andCustomerBirthdayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("customer_birthday <=", value, "customerBirthday");
            return (Criteria) this;
        }

        public Criteria andCustomerBirthdayIn(List<Date> values) {
            addCriterionForJDBCDate("customer_birthday in", values, "customerBirthday");
            return (Criteria) this;
        }

        public Criteria andCustomerBirthdayNotIn(List<Date> values) {
            addCriterionForJDBCDate("customer_birthday not in", values, "customerBirthday");
            return (Criteria) this;
        }

        public Criteria andCustomerBirthdayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("customer_birthday between", value1, value2, "customerBirthday");
            return (Criteria) this;
        }

        public Criteria andCustomerBirthdayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("customer_birthday not between", value1, value2, "customerBirthday");
            return (Criteria) this;
        }

        public Criteria andCustomerScoreIsNull() {
            addCriterion("customer_score is null");
            return (Criteria) this;
        }

        public Criteria andCustomerScoreIsNotNull() {
            addCriterion("customer_score is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerScoreEqualTo(Integer value) {
            addCriterion("customer_score =", value, "customerScore");
            return (Criteria) this;
        }

        public Criteria andCustomerScoreNotEqualTo(Integer value) {
            addCriterion("customer_score <>", value, "customerScore");
            return (Criteria) this;
        }

        public Criteria andCustomerScoreGreaterThan(Integer value) {
            addCriterion("customer_score >", value, "customerScore");
            return (Criteria) this;
        }

        public Criteria andCustomerScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("customer_score >=", value, "customerScore");
            return (Criteria) this;
        }

        public Criteria andCustomerScoreLessThan(Integer value) {
            addCriterion("customer_score <", value, "customerScore");
            return (Criteria) this;
        }

        public Criteria andCustomerScoreLessThanOrEqualTo(Integer value) {
            addCriterion("customer_score <=", value, "customerScore");
            return (Criteria) this;
        }

        public Criteria andCustomerScoreIn(List<Integer> values) {
            addCriterion("customer_score in", values, "customerScore");
            return (Criteria) this;
        }

        public Criteria andCustomerScoreNotIn(List<Integer> values) {
            addCriterion("customer_score not in", values, "customerScore");
            return (Criteria) this;
        }

        public Criteria andCustomerScoreBetween(Integer value1, Integer value2) {
            addCriterion("customer_score between", value1, value2, "customerScore");
            return (Criteria) this;
        }

        public Criteria andCustomerScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("customer_score not between", value1, value2, "customerScore");
            return (Criteria) this;
        }

        public Criteria andInitScoreIsNull() {
            addCriterion("init_score is null");
            return (Criteria) this;
        }

        public Criteria andInitScoreIsNotNull() {
            addCriterion("init_score is not null");
            return (Criteria) this;
        }

        public Criteria andInitScoreEqualTo(Integer value) {
            addCriterion("init_score =", value, "initScore");
            return (Criteria) this;
        }

        public Criteria andInitScoreNotEqualTo(Integer value) {
            addCriterion("init_score <>", value, "initScore");
            return (Criteria) this;
        }

        public Criteria andInitScoreGreaterThan(Integer value) {
            addCriterion("init_score >", value, "initScore");
            return (Criteria) this;
        }

        public Criteria andInitScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("init_score >=", value, "initScore");
            return (Criteria) this;
        }

        public Criteria andInitScoreLessThan(Integer value) {
            addCriterion("init_score <", value, "initScore");
            return (Criteria) this;
        }

        public Criteria andInitScoreLessThanOrEqualTo(Integer value) {
            addCriterion("init_score <=", value, "initScore");
            return (Criteria) this;
        }

        public Criteria andInitScoreIn(List<Integer> values) {
            addCriterion("init_score in", values, "initScore");
            return (Criteria) this;
        }

        public Criteria andInitScoreNotIn(List<Integer> values) {
            addCriterion("init_score not in", values, "initScore");
            return (Criteria) this;
        }

        public Criteria andInitScoreBetween(Integer value1, Integer value2) {
            addCriterion("init_score between", value1, value2, "initScore");
            return (Criteria) this;
        }

        public Criteria andInitScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("init_score not between", value1, value2, "initScore");
            return (Criteria) this;
        }

        public Criteria andCustomerCountryIsNull() {
            addCriterion("customer_country is null");
            return (Criteria) this;
        }

        public Criteria andCustomerCountryIsNotNull() {
            addCriterion("customer_country is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerCountryEqualTo(String value) {
            addCriterion("customer_country =", value, "customerCountry");
            return (Criteria) this;
        }

        public Criteria andCustomerCountryNotEqualTo(String value) {
            addCriterion("customer_country <>", value, "customerCountry");
            return (Criteria) this;
        }

        public Criteria andCustomerCountryGreaterThan(String value) {
            addCriterion("customer_country >", value, "customerCountry");
            return (Criteria) this;
        }

        public Criteria andCustomerCountryGreaterThanOrEqualTo(String value) {
            addCriterion("customer_country >=", value, "customerCountry");
            return (Criteria) this;
        }

        public Criteria andCustomerCountryLessThan(String value) {
            addCriterion("customer_country <", value, "customerCountry");
            return (Criteria) this;
        }

        public Criteria andCustomerCountryLessThanOrEqualTo(String value) {
            addCriterion("customer_country <=", value, "customerCountry");
            return (Criteria) this;
        }

        public Criteria andCustomerCountryLike(String value) {
            addCriterion("customer_country like", value, "customerCountry");
            return (Criteria) this;
        }

        public Criteria andCustomerCountryNotLike(String value) {
            addCriterion("customer_country not like", value, "customerCountry");
            return (Criteria) this;
        }

        public Criteria andCustomerCountryIn(List<String> values) {
            addCriterion("customer_country in", values, "customerCountry");
            return (Criteria) this;
        }

        public Criteria andCustomerCountryNotIn(List<String> values) {
            addCriterion("customer_country not in", values, "customerCountry");
            return (Criteria) this;
        }

        public Criteria andCustomerCountryBetween(String value1, String value2) {
            addCriterion("customer_country between", value1, value2, "customerCountry");
            return (Criteria) this;
        }

        public Criteria andCustomerCountryNotBetween(String value1, String value2) {
            addCriterion("customer_country not between", value1, value2, "customerCountry");
            return (Criteria) this;
        }

        public Criteria andCustomerProvinceIsNull() {
            addCriterion("customer_province is null");
            return (Criteria) this;
        }

        public Criteria andCustomerProvinceIsNotNull() {
            addCriterion("customer_province is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerProvinceEqualTo(String value) {
            addCriterion("customer_province =", value, "customerProvince");
            return (Criteria) this;
        }

        public Criteria andCustomerProvinceNotEqualTo(String value) {
            addCriterion("customer_province <>", value, "customerProvince");
            return (Criteria) this;
        }

        public Criteria andCustomerProvinceGreaterThan(String value) {
            addCriterion("customer_province >", value, "customerProvince");
            return (Criteria) this;
        }

        public Criteria andCustomerProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("customer_province >=", value, "customerProvince");
            return (Criteria) this;
        }

        public Criteria andCustomerProvinceLessThan(String value) {
            addCriterion("customer_province <", value, "customerProvince");
            return (Criteria) this;
        }

        public Criteria andCustomerProvinceLessThanOrEqualTo(String value) {
            addCriterion("customer_province <=", value, "customerProvince");
            return (Criteria) this;
        }

        public Criteria andCustomerProvinceLike(String value) {
            addCriterion("customer_province like", value, "customerProvince");
            return (Criteria) this;
        }

        public Criteria andCustomerProvinceNotLike(String value) {
            addCriterion("customer_province not like", value, "customerProvince");
            return (Criteria) this;
        }

        public Criteria andCustomerProvinceIn(List<String> values) {
            addCriterion("customer_province in", values, "customerProvince");
            return (Criteria) this;
        }

        public Criteria andCustomerProvinceNotIn(List<String> values) {
            addCriterion("customer_province not in", values, "customerProvince");
            return (Criteria) this;
        }

        public Criteria andCustomerProvinceBetween(String value1, String value2) {
            addCriterion("customer_province between", value1, value2, "customerProvince");
            return (Criteria) this;
        }

        public Criteria andCustomerProvinceNotBetween(String value1, String value2) {
            addCriterion("customer_province not between", value1, value2, "customerProvince");
            return (Criteria) this;
        }

        public Criteria andCustomerCityIsNull() {
            addCriterion("customer_city is null");
            return (Criteria) this;
        }

        public Criteria andCustomerCityIsNotNull() {
            addCriterion("customer_city is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerCityEqualTo(String value) {
            addCriterion("customer_city =", value, "customerCity");
            return (Criteria) this;
        }

        public Criteria andCustomerCityNotEqualTo(String value) {
            addCriterion("customer_city <>", value, "customerCity");
            return (Criteria) this;
        }

        public Criteria andCustomerCityGreaterThan(String value) {
            addCriterion("customer_city >", value, "customerCity");
            return (Criteria) this;
        }

        public Criteria andCustomerCityGreaterThanOrEqualTo(String value) {
            addCriterion("customer_city >=", value, "customerCity");
            return (Criteria) this;
        }

        public Criteria andCustomerCityLessThan(String value) {
            addCriterion("customer_city <", value, "customerCity");
            return (Criteria) this;
        }

        public Criteria andCustomerCityLessThanOrEqualTo(String value) {
            addCriterion("customer_city <=", value, "customerCity");
            return (Criteria) this;
        }

        public Criteria andCustomerCityLike(String value) {
            addCriterion("customer_city like", value, "customerCity");
            return (Criteria) this;
        }

        public Criteria andCustomerCityNotLike(String value) {
            addCriterion("customer_city not like", value, "customerCity");
            return (Criteria) this;
        }

        public Criteria andCustomerCityIn(List<String> values) {
            addCriterion("customer_city in", values, "customerCity");
            return (Criteria) this;
        }

        public Criteria andCustomerCityNotIn(List<String> values) {
            addCriterion("customer_city not in", values, "customerCity");
            return (Criteria) this;
        }

        public Criteria andCustomerCityBetween(String value1, String value2) {
            addCriterion("customer_city between", value1, value2, "customerCity");
            return (Criteria) this;
        }

        public Criteria andCustomerCityNotBetween(String value1, String value2) {
            addCriterion("customer_city not between", value1, value2, "customerCity");
            return (Criteria) this;
        }

        public Criteria andCustomerAreaIsNull() {
            addCriterion("customer_area is null");
            return (Criteria) this;
        }

        public Criteria andCustomerAreaIsNotNull() {
            addCriterion("customer_area is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerAreaEqualTo(String value) {
            addCriterion("customer_area =", value, "customerArea");
            return (Criteria) this;
        }

        public Criteria andCustomerAreaNotEqualTo(String value) {
            addCriterion("customer_area <>", value, "customerArea");
            return (Criteria) this;
        }

        public Criteria andCustomerAreaGreaterThan(String value) {
            addCriterion("customer_area >", value, "customerArea");
            return (Criteria) this;
        }

        public Criteria andCustomerAreaGreaterThanOrEqualTo(String value) {
            addCriterion("customer_area >=", value, "customerArea");
            return (Criteria) this;
        }

        public Criteria andCustomerAreaLessThan(String value) {
            addCriterion("customer_area <", value, "customerArea");
            return (Criteria) this;
        }

        public Criteria andCustomerAreaLessThanOrEqualTo(String value) {
            addCriterion("customer_area <=", value, "customerArea");
            return (Criteria) this;
        }

        public Criteria andCustomerAreaLike(String value) {
            addCriterion("customer_area like", value, "customerArea");
            return (Criteria) this;
        }

        public Criteria andCustomerAreaNotLike(String value) {
            addCriterion("customer_area not like", value, "customerArea");
            return (Criteria) this;
        }

        public Criteria andCustomerAreaIn(List<String> values) {
            addCriterion("customer_area in", values, "customerArea");
            return (Criteria) this;
        }

        public Criteria andCustomerAreaNotIn(List<String> values) {
            addCriterion("customer_area not in", values, "customerArea");
            return (Criteria) this;
        }

        public Criteria andCustomerAreaBetween(String value1, String value2) {
            addCriterion("customer_area between", value1, value2, "customerArea");
            return (Criteria) this;
        }

        public Criteria andCustomerAreaNotBetween(String value1, String value2) {
            addCriterion("customer_area not between", value1, value2, "customerArea");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressIsNull() {
            addCriterion("customer_address is null");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressIsNotNull() {
            addCriterion("customer_address is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressEqualTo(String value) {
            addCriterion("customer_address =", value, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressNotEqualTo(String value) {
            addCriterion("customer_address <>", value, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressGreaterThan(String value) {
            addCriterion("customer_address >", value, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressGreaterThanOrEqualTo(String value) {
            addCriterion("customer_address >=", value, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressLessThan(String value) {
            addCriterion("customer_address <", value, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressLessThanOrEqualTo(String value) {
            addCriterion("customer_address <=", value, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressLike(String value) {
            addCriterion("customer_address like", value, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressNotLike(String value) {
            addCriterion("customer_address not like", value, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressIn(List<String> values) {
            addCriterion("customer_address in", values, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressNotIn(List<String> values) {
            addCriterion("customer_address not in", values, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressBetween(String value1, String value2) {
            addCriterion("customer_address between", value1, value2, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressNotBetween(String value1, String value2) {
            addCriterion("customer_address not between", value1, value2, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andActiveFlagIsNull() {
            addCriterion("active_flag is null");
            return (Criteria) this;
        }

        public Criteria andActiveFlagIsNotNull() {
            addCriterion("active_flag is not null");
            return (Criteria) this;
        }

        public Criteria andActiveFlagEqualTo(Byte value) {
            addCriterion("active_flag =", value, "activeFlag");
            return (Criteria) this;
        }

        public Criteria andActiveFlagNotEqualTo(Byte value) {
            addCriterion("active_flag <>", value, "activeFlag");
            return (Criteria) this;
        }

        public Criteria andActiveFlagGreaterThan(Byte value) {
            addCriterion("active_flag >", value, "activeFlag");
            return (Criteria) this;
        }

        public Criteria andActiveFlagGreaterThanOrEqualTo(Byte value) {
            addCriterion("active_flag >=", value, "activeFlag");
            return (Criteria) this;
        }

        public Criteria andActiveFlagLessThan(Byte value) {
            addCriterion("active_flag <", value, "activeFlag");
            return (Criteria) this;
        }

        public Criteria andActiveFlagLessThanOrEqualTo(Byte value) {
            addCriterion("active_flag <=", value, "activeFlag");
            return (Criteria) this;
        }

        public Criteria andActiveFlagIn(List<Byte> values) {
            addCriterion("active_flag in", values, "activeFlag");
            return (Criteria) this;
        }

        public Criteria andActiveFlagNotIn(List<Byte> values) {
            addCriterion("active_flag not in", values, "activeFlag");
            return (Criteria) this;
        }

        public Criteria andActiveFlagBetween(Byte value1, Byte value2) {
            addCriterion("active_flag between", value1, value2, "activeFlag");
            return (Criteria) this;
        }

        public Criteria andActiveFlagNotBetween(Byte value1, Byte value2) {
            addCriterion("active_flag not between", value1, value2, "activeFlag");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNull() {
            addCriterion("shop_id is null");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNotNull() {
            addCriterion("shop_id is not null");
            return (Criteria) this;
        }

        public Criteria andShopIdEqualTo(Integer value) {
            addCriterion("shop_id =", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotEqualTo(Integer value) {
            addCriterion("shop_id <>", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThan(Integer value) {
            addCriterion("shop_id >", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("shop_id >=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThan(Integer value) {
            addCriterion("shop_id <", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThanOrEqualTo(Integer value) {
            addCriterion("shop_id <=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdIn(List<Integer> values) {
            addCriterion("shop_id in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotIn(List<Integer> values) {
            addCriterion("shop_id not in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdBetween(Integer value1, Integer value2) {
            addCriterion("shop_id between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotBetween(Integer value1, Integer value2) {
            addCriterion("shop_id not between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andCreateUidIsNull() {
            addCriterion("create_uid is null");
            return (Criteria) this;
        }

        public Criteria andCreateUidIsNotNull() {
            addCriterion("create_uid is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUidEqualTo(Integer value) {
            addCriterion("create_uid =", value, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidNotEqualTo(Integer value) {
            addCriterion("create_uid <>", value, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidGreaterThan(Integer value) {
            addCriterion("create_uid >", value, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_uid >=", value, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidLessThan(Integer value) {
            addCriterion("create_uid <", value, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidLessThanOrEqualTo(Integer value) {
            addCriterion("create_uid <=", value, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidIn(List<Integer> values) {
            addCriterion("create_uid in", values, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidNotIn(List<Integer> values) {
            addCriterion("create_uid not in", values, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidBetween(Integer value1, Integer value2) {
            addCriterion("create_uid between", value1, value2, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidNotBetween(Integer value1, Integer value2) {
            addCriterion("create_uid not between", value1, value2, "createUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidIsNull() {
            addCriterion("update_uid is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUidIsNotNull() {
            addCriterion("update_uid is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUidEqualTo(Integer value) {
            addCriterion("update_uid =", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotEqualTo(Integer value) {
            addCriterion("update_uid <>", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidGreaterThan(Integer value) {
            addCriterion("update_uid >", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_uid >=", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidLessThan(Integer value) {
            addCriterion("update_uid <", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidLessThanOrEqualTo(Integer value) {
            addCriterion("update_uid <=", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidIn(List<Integer> values) {
            addCriterion("update_uid in", values, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotIn(List<Integer> values) {
            addCriterion("update_uid not in", values, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidBetween(Integer value1, Integer value2) {
            addCriterion("update_uid between", value1, value2, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotBetween(Integer value1, Integer value2) {
            addCriterion("update_uid not between", value1, value2, "updateUid");
            return (Criteria) this;
        }

        public Criteria andStrDescIsNull() {
            addCriterion("str_desc is null");
            return (Criteria) this;
        }

        public Criteria andStrDescIsNotNull() {
            addCriterion("str_desc is not null");
            return (Criteria) this;
        }

        public Criteria andStrDescEqualTo(String value) {
            addCriterion("str_desc =", value, "strDesc");
            return (Criteria) this;
        }

        public Criteria andStrDescNotEqualTo(String value) {
            addCriterion("str_desc <>", value, "strDesc");
            return (Criteria) this;
        }

        public Criteria andStrDescGreaterThan(String value) {
            addCriterion("str_desc >", value, "strDesc");
            return (Criteria) this;
        }

        public Criteria andStrDescGreaterThanOrEqualTo(String value) {
            addCriterion("str_desc >=", value, "strDesc");
            return (Criteria) this;
        }

        public Criteria andStrDescLessThan(String value) {
            addCriterion("str_desc <", value, "strDesc");
            return (Criteria) this;
        }

        public Criteria andStrDescLessThanOrEqualTo(String value) {
            addCriterion("str_desc <=", value, "strDesc");
            return (Criteria) this;
        }

        public Criteria andStrDescLike(String value) {
            addCriterion("str_desc like", value, "strDesc");
            return (Criteria) this;
        }

        public Criteria andStrDescNotLike(String value) {
            addCriterion("str_desc not like", value, "strDesc");
            return (Criteria) this;
        }

        public Criteria andStrDescIn(List<String> values) {
            addCriterion("str_desc in", values, "strDesc");
            return (Criteria) this;
        }

        public Criteria andStrDescNotIn(List<String> values) {
            addCriterion("str_desc not in", values, "strDesc");
            return (Criteria) this;
        }

        public Criteria andStrDescBetween(String value1, String value2) {
            addCriterion("str_desc between", value1, value2, "strDesc");
            return (Criteria) this;
        }

        public Criteria andStrDescNotBetween(String value1, String value2) {
            addCriterion("str_desc not between", value1, value2, "strDesc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_customer
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}