package com.mincrm.entity.model;

import java.util.Date;

public class MbCustomer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.customer_id
     *
     * @mbg.generated
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.customer_tel
     *
     * @mbg.generated
     */
    private String customerTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.customer_name
     *
     * @mbg.generated
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.customer_birthday
     *
     * @mbg.generated
     */
    private Date customerBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.customer_score
     *
     * @mbg.generated
     */
    private Integer customerScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.init_score
     *
     * @mbg.generated
     */
    private Integer initScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.customer_country
     *
     * @mbg.generated
     */
    private String customerCountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.customer_province
     *
     * @mbg.generated
     */
    private String customerProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.customer_city
     *
     * @mbg.generated
     */
    private String customerCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.customer_area
     *
     * @mbg.generated
     */
    private String customerArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.customer_address
     *
     * @mbg.generated
     */
    private String customerAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.active_flag
     *
     * @mbg.generated
     */
    private Byte activeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.shop_id
     *
     * @mbg.generated
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.create_uid
     *
     * @mbg.generated
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.update_uid
     *
     * @mbg.generated
     */
    private Integer updateUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.str_desc
     *
     * @mbg.generated
     */
    private String strDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.customer_id
     *
     * @return the value of mb_customer.customer_id
     *
     * @mbg.generated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.customer_id
     *
     * @param customerId the value for mb_customer.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.customer_tel
     *
     * @return the value of mb_customer.customer_tel
     *
     * @mbg.generated
     */
    public String getCustomerTel() {
        return customerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.customer_tel
     *
     * @param customerTel the value for mb_customer.customer_tel
     *
     * @mbg.generated
     */
    public void setCustomerTel(String customerTel) {
        this.customerTel = customerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.customer_name
     *
     * @return the value of mb_customer.customer_name
     *
     * @mbg.generated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.customer_name
     *
     * @param customerName the value for mb_customer.customer_name
     *
     * @mbg.generated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.customer_birthday
     *
     * @return the value of mb_customer.customer_birthday
     *
     * @mbg.generated
     */
    public Date getCustomerBirthday() {
        return customerBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.customer_birthday
     *
     * @param customerBirthday the value for mb_customer.customer_birthday
     *
     * @mbg.generated
     */
    public void setCustomerBirthday(Date customerBirthday) {
        this.customerBirthday = customerBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.customer_score
     *
     * @return the value of mb_customer.customer_score
     *
     * @mbg.generated
     */
    public Integer getCustomerScore() {
        return customerScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.customer_score
     *
     * @param customerScore the value for mb_customer.customer_score
     *
     * @mbg.generated
     */
    public void setCustomerScore(Integer customerScore) {
        this.customerScore = customerScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.init_score
     *
     * @return the value of mb_customer.init_score
     *
     * @mbg.generated
     */
    public Integer getInitScore() {
        return initScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.init_score
     *
     * @param initScore the value for mb_customer.init_score
     *
     * @mbg.generated
     */
    public void setInitScore(Integer initScore) {
        this.initScore = initScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.customer_country
     *
     * @return the value of mb_customer.customer_country
     *
     * @mbg.generated
     */
    public String getCustomerCountry() {
        return customerCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.customer_country
     *
     * @param customerCountry the value for mb_customer.customer_country
     *
     * @mbg.generated
     */
    public void setCustomerCountry(String customerCountry) {
        this.customerCountry = customerCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.customer_province
     *
     * @return the value of mb_customer.customer_province
     *
     * @mbg.generated
     */
    public String getCustomerProvince() {
        return customerProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.customer_province
     *
     * @param customerProvince the value for mb_customer.customer_province
     *
     * @mbg.generated
     */
    public void setCustomerProvince(String customerProvince) {
        this.customerProvince = customerProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.customer_city
     *
     * @return the value of mb_customer.customer_city
     *
     * @mbg.generated
     */
    public String getCustomerCity() {
        return customerCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.customer_city
     *
     * @param customerCity the value for mb_customer.customer_city
     *
     * @mbg.generated
     */
    public void setCustomerCity(String customerCity) {
        this.customerCity = customerCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.customer_area
     *
     * @return the value of mb_customer.customer_area
     *
     * @mbg.generated
     */
    public String getCustomerArea() {
        return customerArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.customer_area
     *
     * @param customerArea the value for mb_customer.customer_area
     *
     * @mbg.generated
     */
    public void setCustomerArea(String customerArea) {
        this.customerArea = customerArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.customer_address
     *
     * @return the value of mb_customer.customer_address
     *
     * @mbg.generated
     */
    public String getCustomerAddress() {
        return customerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.customer_address
     *
     * @param customerAddress the value for mb_customer.customer_address
     *
     * @mbg.generated
     */
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.active_flag
     *
     * @return the value of mb_customer.active_flag
     *
     * @mbg.generated
     */
    public Byte getActiveFlag() {
        return activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.active_flag
     *
     * @param activeFlag the value for mb_customer.active_flag
     *
     * @mbg.generated
     */
    public void setActiveFlag(Byte activeFlag) {
        this.activeFlag = activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.shop_id
     *
     * @return the value of mb_customer.shop_id
     *
     * @mbg.generated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.shop_id
     *
     * @param shopId the value for mb_customer.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.create_date
     *
     * @return the value of mb_customer.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.create_date
     *
     * @param createDate the value for mb_customer.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.update_date
     *
     * @return the value of mb_customer.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.update_date
     *
     * @param updateDate the value for mb_customer.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.create_uid
     *
     * @return the value of mb_customer.create_uid
     *
     * @mbg.generated
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.create_uid
     *
     * @param createUid the value for mb_customer.create_uid
     *
     * @mbg.generated
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.update_uid
     *
     * @return the value of mb_customer.update_uid
     *
     * @mbg.generated
     */
    public Integer getUpdateUid() {
        return updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.update_uid
     *
     * @param updateUid the value for mb_customer.update_uid
     *
     * @mbg.generated
     */
    public void setUpdateUid(Integer updateUid) {
        this.updateUid = updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.str_desc
     *
     * @return the value of mb_customer.str_desc
     *
     * @mbg.generated
     */
    public String getStrDesc() {
        return strDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.str_desc
     *
     * @param strDesc the value for mb_customer.str_desc
     *
     * @mbg.generated
     */
    public void setStrDesc(String strDesc) {
        this.strDesc = strDesc;
    }
}