package com.mincrm.entity.model;

import java.util.Date;

public class MbOrderScoreExchange {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score_exchange.exchange_id
     *
     * @mbg.generated
     */
    private Integer exchangeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score_exchange.customer_id
     *
     * @mbg.generated
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score_exchange.shop_id
     *
     * @mbg.generated
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score_exchange.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score_exchange.exchange_score
     *
     * @mbg.generated
     */
    private Integer exchangeScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score_exchange.active_flag
     *
     * @mbg.generated
     */
    private Byte activeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score_exchange.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score_exchange.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score_exchange.create_uid
     *
     * @mbg.generated
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score_exchange.update_uid
     *
     * @mbg.generated
     */
    private Integer updateUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score_exchange.str_desc
     *
     * @mbg.generated
     */
    private String strDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score_exchange.exchange_id
     *
     * @return the value of mb_order_score_exchange.exchange_id
     *
     * @mbg.generated
     */
    public Integer getExchangeId() {
        return exchangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score_exchange.exchange_id
     *
     * @param exchangeId the value for mb_order_score_exchange.exchange_id
     *
     * @mbg.generated
     */
    public void setExchangeId(Integer exchangeId) {
        this.exchangeId = exchangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score_exchange.customer_id
     *
     * @return the value of mb_order_score_exchange.customer_id
     *
     * @mbg.generated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score_exchange.customer_id
     *
     * @param customerId the value for mb_order_score_exchange.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score_exchange.shop_id
     *
     * @return the value of mb_order_score_exchange.shop_id
     *
     * @mbg.generated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score_exchange.shop_id
     *
     * @param shopId the value for mb_order_score_exchange.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score_exchange.goods_name
     *
     * @return the value of mb_order_score_exchange.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score_exchange.goods_name
     *
     * @param goodsName the value for mb_order_score_exchange.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score_exchange.exchange_score
     *
     * @return the value of mb_order_score_exchange.exchange_score
     *
     * @mbg.generated
     */
    public Integer getExchangeScore() {
        return exchangeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score_exchange.exchange_score
     *
     * @param exchangeScore the value for mb_order_score_exchange.exchange_score
     *
     * @mbg.generated
     */
    public void setExchangeScore(Integer exchangeScore) {
        this.exchangeScore = exchangeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score_exchange.active_flag
     *
     * @return the value of mb_order_score_exchange.active_flag
     *
     * @mbg.generated
     */
    public Byte getActiveFlag() {
        return activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score_exchange.active_flag
     *
     * @param activeFlag the value for mb_order_score_exchange.active_flag
     *
     * @mbg.generated
     */
    public void setActiveFlag(Byte activeFlag) {
        this.activeFlag = activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score_exchange.create_date
     *
     * @return the value of mb_order_score_exchange.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score_exchange.create_date
     *
     * @param createDate the value for mb_order_score_exchange.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score_exchange.update_date
     *
     * @return the value of mb_order_score_exchange.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score_exchange.update_date
     *
     * @param updateDate the value for mb_order_score_exchange.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score_exchange.create_uid
     *
     * @return the value of mb_order_score_exchange.create_uid
     *
     * @mbg.generated
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score_exchange.create_uid
     *
     * @param createUid the value for mb_order_score_exchange.create_uid
     *
     * @mbg.generated
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score_exchange.update_uid
     *
     * @return the value of mb_order_score_exchange.update_uid
     *
     * @mbg.generated
     */
    public Integer getUpdateUid() {
        return updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score_exchange.update_uid
     *
     * @param updateUid the value for mb_order_score_exchange.update_uid
     *
     * @mbg.generated
     */
    public void setUpdateUid(Integer updateUid) {
        this.updateUid = updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score_exchange.str_desc
     *
     * @return the value of mb_order_score_exchange.str_desc
     *
     * @mbg.generated
     */
    public String getStrDesc() {
        return strDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score_exchange.str_desc
     *
     * @param strDesc the value for mb_order_score_exchange.str_desc
     *
     * @mbg.generated
     */
    public void setStrDesc(String strDesc) {
        this.strDesc = strDesc;
    }
}