package com.mincrm.entity.model;

import java.util.Date;

public class MbOrderScore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score.score_type
     *
     * @mbg.generated
     */
    private Byte scoreType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score.goods_fact_price
     *
     * @mbg.generated
     */
    private Double goodsFactPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score.customer_id
     *
     * @mbg.generated
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score.shop_id
     *
     * @mbg.generated
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score.goods_score
     *
     * @mbg.generated
     */
    private Integer goodsScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score.active_flag
     *
     * @mbg.generated
     */
    private Byte activeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score.create_uid
     *
     * @mbg.generated
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score.update_uid
     *
     * @mbg.generated
     */
    private Integer updateUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order_score.str_desc
     *
     * @mbg.generated
     */
    private String strDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score.order_id
     *
     * @return the value of mb_order_score.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score.order_id
     *
     * @param orderId the value for mb_order_score.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score.score_type
     *
     * @return the value of mb_order_score.score_type
     *
     * @mbg.generated
     */
    public Byte getScoreType() {
        return scoreType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score.score_type
     *
     * @param scoreType the value for mb_order_score.score_type
     *
     * @mbg.generated
     */
    public void setScoreType(Byte scoreType) {
        this.scoreType = scoreType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score.category_id
     *
     * @return the value of mb_order_score.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score.category_id
     *
     * @param categoryId the value for mb_order_score.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score.goods_id
     *
     * @return the value of mb_order_score.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score.goods_id
     *
     * @param goodsId the value for mb_order_score.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score.goods_fact_price
     *
     * @return the value of mb_order_score.goods_fact_price
     *
     * @mbg.generated
     */
    public Double getGoodsFactPrice() {
        return goodsFactPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score.goods_fact_price
     *
     * @param goodsFactPrice the value for mb_order_score.goods_fact_price
     *
     * @mbg.generated
     */
    public void setGoodsFactPrice(Double goodsFactPrice) {
        this.goodsFactPrice = goodsFactPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score.customer_id
     *
     * @return the value of mb_order_score.customer_id
     *
     * @mbg.generated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score.customer_id
     *
     * @param customerId the value for mb_order_score.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score.shop_id
     *
     * @return the value of mb_order_score.shop_id
     *
     * @mbg.generated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score.shop_id
     *
     * @param shopId the value for mb_order_score.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score.goods_score
     *
     * @return the value of mb_order_score.goods_score
     *
     * @mbg.generated
     */
    public Integer getGoodsScore() {
        return goodsScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score.goods_score
     *
     * @param goodsScore the value for mb_order_score.goods_score
     *
     * @mbg.generated
     */
    public void setGoodsScore(Integer goodsScore) {
        this.goodsScore = goodsScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score.active_flag
     *
     * @return the value of mb_order_score.active_flag
     *
     * @mbg.generated
     */
    public Byte getActiveFlag() {
        return activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score.active_flag
     *
     * @param activeFlag the value for mb_order_score.active_flag
     *
     * @mbg.generated
     */
    public void setActiveFlag(Byte activeFlag) {
        this.activeFlag = activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score.create_date
     *
     * @return the value of mb_order_score.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score.create_date
     *
     * @param createDate the value for mb_order_score.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score.update_date
     *
     * @return the value of mb_order_score.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score.update_date
     *
     * @param updateDate the value for mb_order_score.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score.create_uid
     *
     * @return the value of mb_order_score.create_uid
     *
     * @mbg.generated
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score.create_uid
     *
     * @param createUid the value for mb_order_score.create_uid
     *
     * @mbg.generated
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score.update_uid
     *
     * @return the value of mb_order_score.update_uid
     *
     * @mbg.generated
     */
    public Integer getUpdateUid() {
        return updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score.update_uid
     *
     * @param updateUid the value for mb_order_score.update_uid
     *
     * @mbg.generated
     */
    public void setUpdateUid(Integer updateUid) {
        this.updateUid = updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order_score.str_desc
     *
     * @return the value of mb_order_score.str_desc
     *
     * @mbg.generated
     */
    public String getStrDesc() {
        return strDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order_score.str_desc
     *
     * @param strDesc the value for mb_order_score.str_desc
     *
     * @mbg.generated
     */
    public void setStrDesc(String strDesc) {
        this.strDesc = strDesc;
    }
}