package com.mincrm.entity.model;

import java.util.Date;

public class MinAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_account.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_account.account_tel
     *
     * @mbg.generated
     */
    private String accountTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_account.account_pas
     *
     * @mbg.generated
     */
    private String accountPas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_account.account_name
     *
     * @mbg.generated
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_account.active_flag
     *
     * @mbg.generated
     */
    private Byte activeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_account.cdate
     *
     * @mbg.generated
     */
    private Date cdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_account.udate
     *
     * @mbg.generated
     */
    private Date udate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_account.create_uid
     *
     * @mbg.generated
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_account.update_uid
     *
     * @mbg.generated
     */
    private Integer updateUid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_account.uid
     *
     * @return the value of min_account.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_account.uid
     *
     * @param uid the value for min_account.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_account.account_tel
     *
     * @return the value of min_account.account_tel
     *
     * @mbg.generated
     */
    public String getAccountTel() {
        return accountTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_account.account_tel
     *
     * @param accountTel the value for min_account.account_tel
     *
     * @mbg.generated
     */
    public void setAccountTel(String accountTel) {
        this.accountTel = accountTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_account.account_pas
     *
     * @return the value of min_account.account_pas
     *
     * @mbg.generated
     */
    public String getAccountPas() {
        return accountPas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_account.account_pas
     *
     * @param accountPas the value for min_account.account_pas
     *
     * @mbg.generated
     */
    public void setAccountPas(String accountPas) {
        this.accountPas = accountPas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_account.account_name
     *
     * @return the value of min_account.account_name
     *
     * @mbg.generated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_account.account_name
     *
     * @param accountName the value for min_account.account_name
     *
     * @mbg.generated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_account.active_flag
     *
     * @return the value of min_account.active_flag
     *
     * @mbg.generated
     */
    public Byte getActiveFlag() {
        return activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_account.active_flag
     *
     * @param activeFlag the value for min_account.active_flag
     *
     * @mbg.generated
     */
    public void setActiveFlag(Byte activeFlag) {
        this.activeFlag = activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_account.cdate
     *
     * @return the value of min_account.cdate
     *
     * @mbg.generated
     */
    public Date getCdate() {
        return cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_account.cdate
     *
     * @param cdate the value for min_account.cdate
     *
     * @mbg.generated
     */
    public void setCdate(Date cdate) {
        this.cdate = cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_account.udate
     *
     * @return the value of min_account.udate
     *
     * @mbg.generated
     */
    public Date getUdate() {
        return udate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_account.udate
     *
     * @param udate the value for min_account.udate
     *
     * @mbg.generated
     */
    public void setUdate(Date udate) {
        this.udate = udate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_account.create_uid
     *
     * @return the value of min_account.create_uid
     *
     * @mbg.generated
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_account.create_uid
     *
     * @param createUid the value for min_account.create_uid
     *
     * @mbg.generated
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_account.update_uid
     *
     * @return the value of min_account.update_uid
     *
     * @mbg.generated
     */
    public Integer getUpdateUid() {
        return updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_account.update_uid
     *
     * @param updateUid the value for min_account.update_uid
     *
     * @mbg.generated
     */
    public void setUpdateUid(Integer updateUid) {
        this.updateUid = updateUid;
    }
}