package com.mincrm.entity.model;

import java.util.Date;

public class MinCategoryTemplate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_category_template.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_category_template.category_type
     *
     * @mbg.generated
     */
    private Byte categoryType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_category_template.category_type_name
     *
     * @mbg.generated
     */
    private String categoryTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_category_template.min_category
     *
     * @mbg.generated
     */
    private String minCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_category_template.active_flag
     *
     * @mbg.generated
     */
    private Byte activeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_category_template.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_category_template.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_category_template.create_uid
     *
     * @mbg.generated
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_category_template.update_uid
     *
     * @mbg.generated
     */
    private Integer updateUid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_category_template.category_id
     *
     * @return the value of min_category_template.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_category_template.category_id
     *
     * @param categoryId the value for min_category_template.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_category_template.category_type
     *
     * @return the value of min_category_template.category_type
     *
     * @mbg.generated
     */
    public Byte getCategoryType() {
        return categoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_category_template.category_type
     *
     * @param categoryType the value for min_category_template.category_type
     *
     * @mbg.generated
     */
    public void setCategoryType(Byte categoryType) {
        this.categoryType = categoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_category_template.category_type_name
     *
     * @return the value of min_category_template.category_type_name
     *
     * @mbg.generated
     */
    public String getCategoryTypeName() {
        return categoryTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_category_template.category_type_name
     *
     * @param categoryTypeName the value for min_category_template.category_type_name
     *
     * @mbg.generated
     */
    public void setCategoryTypeName(String categoryTypeName) {
        this.categoryTypeName = categoryTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_category_template.min_category
     *
     * @return the value of min_category_template.min_category
     *
     * @mbg.generated
     */
    public String getMinCategory() {
        return minCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_category_template.min_category
     *
     * @param minCategory the value for min_category_template.min_category
     *
     * @mbg.generated
     */
    public void setMinCategory(String minCategory) {
        this.minCategory = minCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_category_template.active_flag
     *
     * @return the value of min_category_template.active_flag
     *
     * @mbg.generated
     */
    public Byte getActiveFlag() {
        return activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_category_template.active_flag
     *
     * @param activeFlag the value for min_category_template.active_flag
     *
     * @mbg.generated
     */
    public void setActiveFlag(Byte activeFlag) {
        this.activeFlag = activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_category_template.create_date
     *
     * @return the value of min_category_template.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_category_template.create_date
     *
     * @param createDate the value for min_category_template.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_category_template.update_date
     *
     * @return the value of min_category_template.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_category_template.update_date
     *
     * @param updateDate the value for min_category_template.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_category_template.create_uid
     *
     * @return the value of min_category_template.create_uid
     *
     * @mbg.generated
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_category_template.create_uid
     *
     * @param createUid the value for min_category_template.create_uid
     *
     * @mbg.generated
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_category_template.update_uid
     *
     * @return the value of min_category_template.update_uid
     *
     * @mbg.generated
     */
    public Integer getUpdateUid() {
        return updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_category_template.update_uid
     *
     * @param updateUid the value for min_category_template.update_uid
     *
     * @mbg.generated
     */
    public void setUpdateUid(Integer updateUid) {
        this.updateUid = updateUid;
    }
}