package com.mincrm.entity.model;

import java.util.Date;

public class MinGoodsTemplate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_goods_template.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_goods_template.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_goods_template.category_type
     *
     * @mbg.generated
     */
    private Byte categoryType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_goods_template.goods_purchase_price
     *
     * @mbg.generated
     */
    private Double goodsPurchasePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_goods_template.goods_sale_price
     *
     * @mbg.generated
     */
    private Double goodsSalePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_goods_template.min_category
     *
     * @mbg.generated
     */
    private String minCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_goods_template.active_flag
     *
     * @mbg.generated
     */
    private Byte activeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_goods_template.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_goods_template.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_goods_template.create_uid
     *
     * @mbg.generated
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_goods_template.update_uid
     *
     * @mbg.generated
     */
    private Integer updateUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_goods_template.goods_version
     *
     * @mbg.generated
     */
    private String goodsVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_goods_template.goods_id
     *
     * @return the value of min_goods_template.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_goods_template.goods_id
     *
     * @param goodsId the value for min_goods_template.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_goods_template.goods_name
     *
     * @return the value of min_goods_template.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_goods_template.goods_name
     *
     * @param goodsName the value for min_goods_template.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_goods_template.category_type
     *
     * @return the value of min_goods_template.category_type
     *
     * @mbg.generated
     */
    public Byte getCategoryType() {
        return categoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_goods_template.category_type
     *
     * @param categoryType the value for min_goods_template.category_type
     *
     * @mbg.generated
     */
    public void setCategoryType(Byte categoryType) {
        this.categoryType = categoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_goods_template.goods_purchase_price
     *
     * @return the value of min_goods_template.goods_purchase_price
     *
     * @mbg.generated
     */
    public Double getGoodsPurchasePrice() {
        return goodsPurchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_goods_template.goods_purchase_price
     *
     * @param goodsPurchasePrice the value for min_goods_template.goods_purchase_price
     *
     * @mbg.generated
     */
    public void setGoodsPurchasePrice(Double goodsPurchasePrice) {
        this.goodsPurchasePrice = goodsPurchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_goods_template.goods_sale_price
     *
     * @return the value of min_goods_template.goods_sale_price
     *
     * @mbg.generated
     */
    public Double getGoodsSalePrice() {
        return goodsSalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_goods_template.goods_sale_price
     *
     * @param goodsSalePrice the value for min_goods_template.goods_sale_price
     *
     * @mbg.generated
     */
    public void setGoodsSalePrice(Double goodsSalePrice) {
        this.goodsSalePrice = goodsSalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_goods_template.min_category
     *
     * @return the value of min_goods_template.min_category
     *
     * @mbg.generated
     */
    public String getMinCategory() {
        return minCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_goods_template.min_category
     *
     * @param minCategory the value for min_goods_template.min_category
     *
     * @mbg.generated
     */
    public void setMinCategory(String minCategory) {
        this.minCategory = minCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_goods_template.active_flag
     *
     * @return the value of min_goods_template.active_flag
     *
     * @mbg.generated
     */
    public Byte getActiveFlag() {
        return activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_goods_template.active_flag
     *
     * @param activeFlag the value for min_goods_template.active_flag
     *
     * @mbg.generated
     */
    public void setActiveFlag(Byte activeFlag) {
        this.activeFlag = activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_goods_template.create_date
     *
     * @return the value of min_goods_template.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_goods_template.create_date
     *
     * @param createDate the value for min_goods_template.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_goods_template.update_date
     *
     * @return the value of min_goods_template.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_goods_template.update_date
     *
     * @param updateDate the value for min_goods_template.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_goods_template.create_uid
     *
     * @return the value of min_goods_template.create_uid
     *
     * @mbg.generated
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_goods_template.create_uid
     *
     * @param createUid the value for min_goods_template.create_uid
     *
     * @mbg.generated
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_goods_template.update_uid
     *
     * @return the value of min_goods_template.update_uid
     *
     * @mbg.generated
     */
    public Integer getUpdateUid() {
        return updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_goods_template.update_uid
     *
     * @param updateUid the value for min_goods_template.update_uid
     *
     * @mbg.generated
     */
    public void setUpdateUid(Integer updateUid) {
        this.updateUid = updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_goods_template.goods_version
     *
     * @return the value of min_goods_template.goods_version
     *
     * @mbg.generated
     */
    public String getGoodsVersion() {
        return goodsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_goods_template.goods_version
     *
     * @param goodsVersion the value for min_goods_template.goods_version
     *
     * @mbg.generated
     */
    public void setGoodsVersion(String goodsVersion) {
        this.goodsVersion = goodsVersion;
    }
}