package com.mincrm.entity.model;

import java.util.Date;

public class MinShop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_shop.shop_id
     *
     * @mbg.generated
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_shop.shop_type
     *
     * @mbg.generated
     */
    private Byte shopType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_shop.shop_name
     *
     * @mbg.generated
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_shop.shop_country
     *
     * @mbg.generated
     */
    private String shopCountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_shop.shop_province
     *
     * @mbg.generated
     */
    private String shopProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_shop.shop_city
     *
     * @mbg.generated
     */
    private String shopCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_shop.shop_area
     *
     * @mbg.generated
     */
    private String shopArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_shop.shop_address
     *
     * @mbg.generated
     */
    private String shopAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_shop.active_flag
     *
     * @mbg.generated
     */
    private Byte activeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_shop.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_shop.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_shop.create_uid
     *
     * @mbg.generated
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_shop.update_uid
     *
     * @mbg.generated
     */
    private Integer updateUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_shop.str_desc
     *
     * @mbg.generated
     */
    private String strDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_shop.shop_id
     *
     * @return the value of min_shop.shop_id
     *
     * @mbg.generated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_shop.shop_id
     *
     * @param shopId the value for min_shop.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_shop.shop_type
     *
     * @return the value of min_shop.shop_type
     *
     * @mbg.generated
     */
    public Byte getShopType() {
        return shopType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_shop.shop_type
     *
     * @param shopType the value for min_shop.shop_type
     *
     * @mbg.generated
     */
    public void setShopType(Byte shopType) {
        this.shopType = shopType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_shop.shop_name
     *
     * @return the value of min_shop.shop_name
     *
     * @mbg.generated
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_shop.shop_name
     *
     * @param shopName the value for min_shop.shop_name
     *
     * @mbg.generated
     */
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_shop.shop_country
     *
     * @return the value of min_shop.shop_country
     *
     * @mbg.generated
     */
    public String getShopCountry() {
        return shopCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_shop.shop_country
     *
     * @param shopCountry the value for min_shop.shop_country
     *
     * @mbg.generated
     */
    public void setShopCountry(String shopCountry) {
        this.shopCountry = shopCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_shop.shop_province
     *
     * @return the value of min_shop.shop_province
     *
     * @mbg.generated
     */
    public String getShopProvince() {
        return shopProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_shop.shop_province
     *
     * @param shopProvince the value for min_shop.shop_province
     *
     * @mbg.generated
     */
    public void setShopProvince(String shopProvince) {
        this.shopProvince = shopProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_shop.shop_city
     *
     * @return the value of min_shop.shop_city
     *
     * @mbg.generated
     */
    public String getShopCity() {
        return shopCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_shop.shop_city
     *
     * @param shopCity the value for min_shop.shop_city
     *
     * @mbg.generated
     */
    public void setShopCity(String shopCity) {
        this.shopCity = shopCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_shop.shop_area
     *
     * @return the value of min_shop.shop_area
     *
     * @mbg.generated
     */
    public String getShopArea() {
        return shopArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_shop.shop_area
     *
     * @param shopArea the value for min_shop.shop_area
     *
     * @mbg.generated
     */
    public void setShopArea(String shopArea) {
        this.shopArea = shopArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_shop.shop_address
     *
     * @return the value of min_shop.shop_address
     *
     * @mbg.generated
     */
    public String getShopAddress() {
        return shopAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_shop.shop_address
     *
     * @param shopAddress the value for min_shop.shop_address
     *
     * @mbg.generated
     */
    public void setShopAddress(String shopAddress) {
        this.shopAddress = shopAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_shop.active_flag
     *
     * @return the value of min_shop.active_flag
     *
     * @mbg.generated
     */
    public Byte getActiveFlag() {
        return activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_shop.active_flag
     *
     * @param activeFlag the value for min_shop.active_flag
     *
     * @mbg.generated
     */
    public void setActiveFlag(Byte activeFlag) {
        this.activeFlag = activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_shop.create_date
     *
     * @return the value of min_shop.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_shop.create_date
     *
     * @param createDate the value for min_shop.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_shop.update_date
     *
     * @return the value of min_shop.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_shop.update_date
     *
     * @param updateDate the value for min_shop.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_shop.create_uid
     *
     * @return the value of min_shop.create_uid
     *
     * @mbg.generated
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_shop.create_uid
     *
     * @param createUid the value for min_shop.create_uid
     *
     * @mbg.generated
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_shop.update_uid
     *
     * @return the value of min_shop.update_uid
     *
     * @mbg.generated
     */
    public Integer getUpdateUid() {
        return updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_shop.update_uid
     *
     * @param updateUid the value for min_shop.update_uid
     *
     * @mbg.generated
     */
    public void setUpdateUid(Integer updateUid) {
        this.updateUid = updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_shop.str_desc
     *
     * @return the value of min_shop.str_desc
     *
     * @mbg.generated
     */
    public String getStrDesc() {
        return strDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_shop.str_desc
     *
     * @param strDesc the value for min_shop.str_desc
     *
     * @mbg.generated
     */
    public void setStrDesc(String strDesc) {
        this.strDesc = strDesc;
    }
}