package com.mincrm.entity.model;

import java.util.Date;

public class MinVerification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_verification.vid
     *
     * @mbg.generated
     */
    private Integer vid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_verification.verification_code
     *
     * @mbg.generated
     */
    private String verificationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_verification.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_verification.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_verification.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_verification.create_uid
     *
     * @mbg.generated
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_verification.sessionid
     *
     * @mbg.generated
     */
    private String sessionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_verification.minute
     *
     * @mbg.generated
     */
    private Integer minute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_verification.vtype
     *
     * @mbg.generated
     */
    private Integer vtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_verification.vid
     *
     * @return the value of min_verification.vid
     *
     * @mbg.generated
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_verification.vid
     *
     * @param vid the value for min_verification.vid
     *
     * @mbg.generated
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_verification.verification_code
     *
     * @return the value of min_verification.verification_code
     *
     * @mbg.generated
     */
    public String getVerificationCode() {
        return verificationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_verification.verification_code
     *
     * @param verificationCode the value for min_verification.verification_code
     *
     * @mbg.generated
     */
    public void setVerificationCode(String verificationCode) {
        this.verificationCode = verificationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_verification.tel
     *
     * @return the value of min_verification.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_verification.tel
     *
     * @param tel the value for min_verification.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_verification.ip
     *
     * @return the value of min_verification.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_verification.ip
     *
     * @param ip the value for min_verification.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_verification.create_date
     *
     * @return the value of min_verification.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_verification.create_date
     *
     * @param createDate the value for min_verification.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_verification.create_uid
     *
     * @return the value of min_verification.create_uid
     *
     * @mbg.generated
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_verification.create_uid
     *
     * @param createUid the value for min_verification.create_uid
     *
     * @mbg.generated
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_verification.sessionid
     *
     * @return the value of min_verification.sessionid
     *
     * @mbg.generated
     */
    public String getSessionid() {
        return sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_verification.sessionid
     *
     * @param sessionid the value for min_verification.sessionid
     *
     * @mbg.generated
     */
    public void setSessionid(String sessionid) {
        this.sessionid = sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_verification.minute
     *
     * @return the value of min_verification.minute
     *
     * @mbg.generated
     */
    public Integer getMinute() {
        return minute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_verification.minute
     *
     * @param minute the value for min_verification.minute
     *
     * @mbg.generated
     */
    public void setMinute(Integer minute) {
        this.minute = minute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_verification.vtype
     *
     * @return the value of min_verification.vtype
     *
     * @mbg.generated
     */
    public Integer getVtype() {
        return vtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_verification.vtype
     *
     * @param vtype the value for min_verification.vtype
     *
     * @mbg.generated
     */
    public void setVtype(Integer vtype) {
        this.vtype = vtype;
    }
}