package com.mincrm.entity.model;

import java.util.Date;

public class VAccountnameShopRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_accountname_shop_role.account_tel
     *
     * @mbg.generated
     */
    private String accountTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_accountname_shop_role.account_name
     *
     * @mbg.generated
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_accountname_shop_role.shop_id
     *
     * @mbg.generated
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_accountname_shop_role.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_accountname_shop_role.role_type
     *
     * @mbg.generated
     */
    private Byte roleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_accountname_shop_role.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_accountname_shop_role.active_flag
     *
     * @mbg.generated
     */
    private Byte activeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_accountname_shop_role.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_accountname_shop_role.create_uid
     *
     * @mbg.generated
     */
    private Integer createUid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_accountname_shop_role.account_tel
     *
     * @return the value of v_accountname_shop_role.account_tel
     *
     * @mbg.generated
     */
    public String getAccountTel() {
        return accountTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_accountname_shop_role.account_tel
     *
     * @param accountTel the value for v_accountname_shop_role.account_tel
     *
     * @mbg.generated
     */
    public void setAccountTel(String accountTel) {
        this.accountTel = accountTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_accountname_shop_role.account_name
     *
     * @return the value of v_accountname_shop_role.account_name
     *
     * @mbg.generated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_accountname_shop_role.account_name
     *
     * @param accountName the value for v_accountname_shop_role.account_name
     *
     * @mbg.generated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_accountname_shop_role.shop_id
     *
     * @return the value of v_accountname_shop_role.shop_id
     *
     * @mbg.generated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_accountname_shop_role.shop_id
     *
     * @param shopId the value for v_accountname_shop_role.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_accountname_shop_role.uid
     *
     * @return the value of v_accountname_shop_role.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_accountname_shop_role.uid
     *
     * @param uid the value for v_accountname_shop_role.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_accountname_shop_role.role_type
     *
     * @return the value of v_accountname_shop_role.role_type
     *
     * @mbg.generated
     */
    public Byte getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_accountname_shop_role.role_type
     *
     * @param roleType the value for v_accountname_shop_role.role_type
     *
     * @mbg.generated
     */
    public void setRoleType(Byte roleType) {
        this.roleType = roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_accountname_shop_role.role_id
     *
     * @return the value of v_accountname_shop_role.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_accountname_shop_role.role_id
     *
     * @param roleId the value for v_accountname_shop_role.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_accountname_shop_role.active_flag
     *
     * @return the value of v_accountname_shop_role.active_flag
     *
     * @mbg.generated
     */
    public Byte getActiveFlag() {
        return activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_accountname_shop_role.active_flag
     *
     * @param activeFlag the value for v_accountname_shop_role.active_flag
     *
     * @mbg.generated
     */
    public void setActiveFlag(Byte activeFlag) {
        this.activeFlag = activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_accountname_shop_role.create_date
     *
     * @return the value of v_accountname_shop_role.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_accountname_shop_role.create_date
     *
     * @param createDate the value for v_accountname_shop_role.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_accountname_shop_role.create_uid
     *
     * @return the value of v_accountname_shop_role.create_uid
     *
     * @mbg.generated
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_accountname_shop_role.create_uid
     *
     * @param createUid the value for v_accountname_shop_role.create_uid
     *
     * @mbg.generated
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }
}