package com.mincrm.entity.model;

import java.util.Date;

public class VMbOrderScoreExchange {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_mb_order_score_exchange.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_mb_order_score_exchange.customer_id
     *
     * @mbg.generated
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_mb_order_score_exchange.customer_name
     *
     * @mbg.generated
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_mb_order_score_exchange.customer_tel
     *
     * @mbg.generated
     */
    private String customerTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_mb_order_score_exchange.goods_fact_price
     *
     * @mbg.generated
     */
    private Double goodsFactPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_mb_order_score_exchange.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_mb_order_score_exchange.create_uid
     *
     * @mbg.generated
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_mb_order_score_exchange.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_mb_order_score_exchange.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_mb_order_score_exchange.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_mb_order_score_exchange.goods_version
     *
     * @mbg.generated
     */
    private String goodsVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_mb_order_score_exchange.score_type
     *
     * @mbg.generated
     */
    private Byte scoreType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_mb_order_score_exchange.active_flag
     *
     * @mbg.generated
     */
    private Byte activeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_mb_order_score_exchange.shop_id
     *
     * @mbg.generated
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_mb_order_score_exchange.goods_score
     *
     * @mbg.generated
     */
    private Integer goodsScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_mb_order_score_exchange.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_mb_order_score_exchange.update_uid
     *
     * @mbg.generated
     */
    private Integer updateUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_mb_order_score_exchange.goods_purchase_price
     *
     * @mbg.generated
     */
    private Double goodsPurchasePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_mb_order_score_exchange.goods_sale_price
     *
     * @mbg.generated
     */
    private Double goodsSalePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_mb_order_score_exchange.str_desc
     *
     * @mbg.generated
     */
    private String strDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_mb_order_score_exchange.customer_score
     *
     * @mbg.generated
     */
    private Integer customerScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_mb_order_score_exchange.order_id
     *
     * @return the value of v_mb_order_score_exchange.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_mb_order_score_exchange.order_id
     *
     * @param orderId the value for v_mb_order_score_exchange.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_mb_order_score_exchange.customer_id
     *
     * @return the value of v_mb_order_score_exchange.customer_id
     *
     * @mbg.generated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_mb_order_score_exchange.customer_id
     *
     * @param customerId the value for v_mb_order_score_exchange.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_mb_order_score_exchange.customer_name
     *
     * @return the value of v_mb_order_score_exchange.customer_name
     *
     * @mbg.generated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_mb_order_score_exchange.customer_name
     *
     * @param customerName the value for v_mb_order_score_exchange.customer_name
     *
     * @mbg.generated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_mb_order_score_exchange.customer_tel
     *
     * @return the value of v_mb_order_score_exchange.customer_tel
     *
     * @mbg.generated
     */
    public String getCustomerTel() {
        return customerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_mb_order_score_exchange.customer_tel
     *
     * @param customerTel the value for v_mb_order_score_exchange.customer_tel
     *
     * @mbg.generated
     */
    public void setCustomerTel(String customerTel) {
        this.customerTel = customerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_mb_order_score_exchange.goods_fact_price
     *
     * @return the value of v_mb_order_score_exchange.goods_fact_price
     *
     * @mbg.generated
     */
    public Double getGoodsFactPrice() {
        return goodsFactPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_mb_order_score_exchange.goods_fact_price
     *
     * @param goodsFactPrice the value for v_mb_order_score_exchange.goods_fact_price
     *
     * @mbg.generated
     */
    public void setGoodsFactPrice(Double goodsFactPrice) {
        this.goodsFactPrice = goodsFactPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_mb_order_score_exchange.create_date
     *
     * @return the value of v_mb_order_score_exchange.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_mb_order_score_exchange.create_date
     *
     * @param createDate the value for v_mb_order_score_exchange.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_mb_order_score_exchange.create_uid
     *
     * @return the value of v_mb_order_score_exchange.create_uid
     *
     * @mbg.generated
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_mb_order_score_exchange.create_uid
     *
     * @param createUid the value for v_mb_order_score_exchange.create_uid
     *
     * @mbg.generated
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_mb_order_score_exchange.category_id
     *
     * @return the value of v_mb_order_score_exchange.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_mb_order_score_exchange.category_id
     *
     * @param categoryId the value for v_mb_order_score_exchange.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_mb_order_score_exchange.goods_id
     *
     * @return the value of v_mb_order_score_exchange.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_mb_order_score_exchange.goods_id
     *
     * @param goodsId the value for v_mb_order_score_exchange.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_mb_order_score_exchange.goods_name
     *
     * @return the value of v_mb_order_score_exchange.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_mb_order_score_exchange.goods_name
     *
     * @param goodsName the value for v_mb_order_score_exchange.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_mb_order_score_exchange.goods_version
     *
     * @return the value of v_mb_order_score_exchange.goods_version
     *
     * @mbg.generated
     */
    public String getGoodsVersion() {
        return goodsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_mb_order_score_exchange.goods_version
     *
     * @param goodsVersion the value for v_mb_order_score_exchange.goods_version
     *
     * @mbg.generated
     */
    public void setGoodsVersion(String goodsVersion) {
        this.goodsVersion = goodsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_mb_order_score_exchange.score_type
     *
     * @return the value of v_mb_order_score_exchange.score_type
     *
     * @mbg.generated
     */
    public Byte getScoreType() {
        return scoreType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_mb_order_score_exchange.score_type
     *
     * @param scoreType the value for v_mb_order_score_exchange.score_type
     *
     * @mbg.generated
     */
    public void setScoreType(Byte scoreType) {
        this.scoreType = scoreType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_mb_order_score_exchange.active_flag
     *
     * @return the value of v_mb_order_score_exchange.active_flag
     *
     * @mbg.generated
     */
    public Byte getActiveFlag() {
        return activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_mb_order_score_exchange.active_flag
     *
     * @param activeFlag the value for v_mb_order_score_exchange.active_flag
     *
     * @mbg.generated
     */
    public void setActiveFlag(Byte activeFlag) {
        this.activeFlag = activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_mb_order_score_exchange.shop_id
     *
     * @return the value of v_mb_order_score_exchange.shop_id
     *
     * @mbg.generated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_mb_order_score_exchange.shop_id
     *
     * @param shopId the value for v_mb_order_score_exchange.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_mb_order_score_exchange.goods_score
     *
     * @return the value of v_mb_order_score_exchange.goods_score
     *
     * @mbg.generated
     */
    public Integer getGoodsScore() {
        return goodsScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_mb_order_score_exchange.goods_score
     *
     * @param goodsScore the value for v_mb_order_score_exchange.goods_score
     *
     * @mbg.generated
     */
    public void setGoodsScore(Integer goodsScore) {
        this.goodsScore = goodsScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_mb_order_score_exchange.update_date
     *
     * @return the value of v_mb_order_score_exchange.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_mb_order_score_exchange.update_date
     *
     * @param updateDate the value for v_mb_order_score_exchange.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_mb_order_score_exchange.update_uid
     *
     * @return the value of v_mb_order_score_exchange.update_uid
     *
     * @mbg.generated
     */
    public Integer getUpdateUid() {
        return updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_mb_order_score_exchange.update_uid
     *
     * @param updateUid the value for v_mb_order_score_exchange.update_uid
     *
     * @mbg.generated
     */
    public void setUpdateUid(Integer updateUid) {
        this.updateUid = updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_mb_order_score_exchange.goods_purchase_price
     *
     * @return the value of v_mb_order_score_exchange.goods_purchase_price
     *
     * @mbg.generated
     */
    public Double getGoodsPurchasePrice() {
        return goodsPurchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_mb_order_score_exchange.goods_purchase_price
     *
     * @param goodsPurchasePrice the value for v_mb_order_score_exchange.goods_purchase_price
     *
     * @mbg.generated
     */
    public void setGoodsPurchasePrice(Double goodsPurchasePrice) {
        this.goodsPurchasePrice = goodsPurchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_mb_order_score_exchange.goods_sale_price
     *
     * @return the value of v_mb_order_score_exchange.goods_sale_price
     *
     * @mbg.generated
     */
    public Double getGoodsSalePrice() {
        return goodsSalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_mb_order_score_exchange.goods_sale_price
     *
     * @param goodsSalePrice the value for v_mb_order_score_exchange.goods_sale_price
     *
     * @mbg.generated
     */
    public void setGoodsSalePrice(Double goodsSalePrice) {
        this.goodsSalePrice = goodsSalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_mb_order_score_exchange.str_desc
     *
     * @return the value of v_mb_order_score_exchange.str_desc
     *
     * @mbg.generated
     */
    public String getStrDesc() {
        return strDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_mb_order_score_exchange.str_desc
     *
     * @param strDesc the value for v_mb_order_score_exchange.str_desc
     *
     * @mbg.generated
     */
    public void setStrDesc(String strDesc) {
        this.strDesc = strDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_mb_order_score_exchange.customer_score
     *
     * @return the value of v_mb_order_score_exchange.customer_score
     *
     * @mbg.generated
     */
    public Integer getCustomerScore() {
        return customerScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_mb_order_score_exchange.customer_score
     *
     * @param customerScore the value for v_mb_order_score_exchange.customer_score
     *
     * @mbg.generated
     */
    public void setCustomerScore(Integer customerScore) {
        this.customerScore = customerScore;
    }
}