package com.mincrm.entity.dao;

import com.mincrm.entity.model.CrmAccount;
import com.mincrm.entity.model.CrmAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;

@Mapper
public interface CrmAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_account
     *
     * @mbg.generated
     */
    long countByExample(CrmAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_account
     *
     * @mbg.generated
     */
    int deleteByExample(CrmAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_account
     *
     * @mbg.generated
     */
    @Insert({
        "insert into crm_account (tenant_id, account_tel, ",
        "account_pas, account_name, ",
        "active_flag, create_date, ",
        "create_uid, update_date, ",
        "update_uid)",
        "values (#{tenantId,jdbcType=INTEGER}, #{accountTel,jdbcType=VARCHAR}, ",
        "#{accountPas,jdbcType=VARCHAR}, #{accountName,jdbcType=VARCHAR}, ",
        "#{activeFlag,jdbcType=BIT}, #{createDate,jdbcType=TIMESTAMP}, ",
        "#{createUid,jdbcType=INTEGER}, #{updateDate,jdbcType=TIMESTAMP}, ",
        "#{updateUid,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="uid", before=false, resultType=Integer.class)
    int insert(CrmAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_account
     *
     * @mbg.generated
     */
    int insertSelective(CrmAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_account
     *
     * @mbg.generated
     */
    List<CrmAccount> selectByExample(CrmAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_account
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CrmAccount record, @Param("example") CrmAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_account
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CrmAccount record, @Param("example") CrmAccountExample example);
}