package com.mincrm.entity.dao;

import com.mincrm.entity.model.CrmTenant;
import com.mincrm.entity.model.CrmTenantExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;

@Mapper
public interface CrmTenantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_tenant
     *
     * @mbg.generated
     */
    long countByExample(CrmTenantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_tenant
     *
     * @mbg.generated
     */
    int deleteByExample(CrmTenantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_tenant
     *
     * @mbg.generated
     */
    @Insert({
        "insert into crm_tenant (tenant_name, tenant_tel, ",
        "tenant_email, tenant_address, ",
        "active_flag, create_date, ",
        "create_uid, update_date, ",
        "update_uid)",
        "values (#{tenantName,jdbcType=VARCHAR}, #{tenantTel,jdbcType=VARCHAR}, ",
        "#{tenantEmail,jdbcType=VARCHAR}, #{tenantAddress,jdbcType=VARCHAR}, ",
        "#{activeFlag,jdbcType=BIT}, #{createDate,jdbcType=TIMESTAMP}, ",
        "#{createUid,jdbcType=INTEGER}, #{updateDate,jdbcType=TIMESTAMP}, ",
        "#{updateUid,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(CrmTenant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_tenant
     *
     * @mbg.generated
     */
    int insertSelective(CrmTenant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_tenant
     *
     * @mbg.generated
     */
    List<CrmTenant> selectByExample(CrmTenantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_tenant
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CrmTenant record, @Param("example") CrmTenantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_tenant
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CrmTenant record, @Param("example") CrmTenantExample example);
}