package com.mincrm.entity.dao;

import com.mincrm.entity.model.MbCategory;
import com.mincrm.entity.model.MbCategoryExample;
import java.util.List;

import org.apache.ibatis.annotations.*;

@Mapper
public interface MbCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_category
     *
     * @mbg.generated
     */
    long countByExample(MbCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_category
     *
     * @mbg.generated
     */
    int deleteByExample(MbCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_category
     *
     * @mbg.generated
     */
    @Delete({
        "delete from mb_category",
        "where category_id = #{categoryId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_category
     *
     * @mbg.generated
     */
    @Insert({
        "insert into mb_category (category_name, shop_id, ",
        "active_flag, create_date, ",
        "update_date, create_uid, ",
        "update_uid)",
        "values (#{categoryName,jdbcType=VARCHAR}, #{shopId,jdbcType=INTEGER}, ",
        "#{activeFlag,jdbcType=TINYINT}, #{createDate,jdbcType=TIMESTAMP}, ",
        "#{updateDate,jdbcType=TIMESTAMP}, #{createUid,jdbcType=INTEGER}, ",
        "#{updateUid,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="categoryId", before=false, resultType=Integer.class)
    int insert(MbCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_category
     *
     * @mbg.generated
     */
    int insertSelective(MbCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_category
     *
     * @mbg.generated
     */
    List<MbCategory> selectByExample(MbCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_category
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "category_id, category_name, shop_id, active_flag, create_date, update_date, ",
        "create_uid, update_uid",
        "from mb_category",
        "where category_id = #{categoryId,jdbcType=INTEGER}"
    })
    @ResultMap("com.mincrm.entity.dao.MbCategoryMapper.BaseResultMap")
    MbCategory selectByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MbCategory record, @Param("example") MbCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MbCategory record, @Param("example") MbCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MbCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_category
     *
     * @mbg.generated
     */
    @Update({
        "update mb_category",
        "set category_name = #{categoryName,jdbcType=VARCHAR},",
          "shop_id = #{shopId,jdbcType=INTEGER},",
          "active_flag = #{activeFlag,jdbcType=TINYINT},",
          "create_date = #{createDate,jdbcType=TIMESTAMP},",
          "update_date = #{updateDate,jdbcType=TIMESTAMP},",
          "create_uid = #{createUid,jdbcType=INTEGER},",
          "update_uid = #{updateUid,jdbcType=INTEGER}",
        "where category_id = #{categoryId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MbCategory record);

    List<MbCategory>  selectmbCategoryListByshopid(MbCategoryExample example);

}