package com.mincrm.entity.dao;

import com.mincrm.entity.model.MbCustomer;
import com.mincrm.entity.model.MbCustomerExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.*;

@Mapper
public interface MbCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    long countByExample(MbCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    int deleteByExample(MbCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    @Delete({
        "delete from mb_customer",
        "where customer_id = #{customerId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    @Insert({
        "insert into mb_customer (customer_tel, customer_name, ",
        "customer_birthday, customer_score, ",
        "init_score, customer_country, ",
        "customer_province, customer_city, ",
        "customer_area, customer_address, ",
        "active_flag, shop_id, ",
        "create_date, update_date, ",
        "create_uid, update_uid, ",
        "str_desc)",
        "values (#{customerTel,jdbcType=VARCHAR}, #{customerName,jdbcType=VARCHAR}, ",
        "#{customerBirthday,jdbcType=DATE}, #{customerScore,jdbcType=INTEGER}, ",
        "#{initScore,jdbcType=INTEGER}, #{customerCountry,jdbcType=VARCHAR}, ",
        "#{customerProvince,jdbcType=VARCHAR}, #{customerCity,jdbcType=VARCHAR}, ",
        "#{customerArea,jdbcType=VARCHAR}, #{customerAddress,jdbcType=VARCHAR}, ",
        "#{activeFlag,jdbcType=TINYINT}, #{shopId,jdbcType=INTEGER}, ",
        "#{createDate,jdbcType=TIMESTAMP}, #{updateDate,jdbcType=TIMESTAMP}, ",
        "#{createUid,jdbcType=INTEGER}, #{updateUid,jdbcType=INTEGER}, ",
        "#{strDesc,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="customerId", before=false, resultType=Integer.class)
    int insert(MbCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    int insertSelective(MbCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    List<MbCustomer> selectByExample(MbCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "customer_id, customer_tel, customer_name, customer_birthday, customer_score, ",
        "init_score, customer_country, customer_province, customer_city, customer_area, ",
        "customer_address, active_flag, shop_id, create_date, update_date, create_uid, ",
        "update_uid, str_desc",
        "from mb_customer",
        "where customer_id = #{customerId,jdbcType=INTEGER}"
    })
    @ResultMap("com.mincrm.entity.dao.MbCustomerMapper.BaseResultMap")
    MbCustomer selectByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MbCustomer record, @Param("example") MbCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MbCustomer record, @Param("example") MbCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MbCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_customer
     *
     * @mbg.generated
     */
    @Update({
        "update mb_customer",
        "set customer_tel = #{customerTel,jdbcType=VARCHAR},",
          "customer_name = #{customerName,jdbcType=VARCHAR},",
          "customer_birthday = #{customerBirthday,jdbcType=DATE},",
          "customer_score = #{customerScore,jdbcType=INTEGER},",
          "init_score = #{initScore,jdbcType=INTEGER},",
          "customer_country = #{customerCountry,jdbcType=VARCHAR},",
          "customer_province = #{customerProvince,jdbcType=VARCHAR},",
          "customer_city = #{customerCity,jdbcType=VARCHAR},",
          "customer_area = #{customerArea,jdbcType=VARCHAR},",
          "customer_address = #{customerAddress,jdbcType=VARCHAR},",
          "active_flag = #{activeFlag,jdbcType=TINYINT},",
          "shop_id = #{shopId,jdbcType=INTEGER},",
          "create_date = #{createDate,jdbcType=TIMESTAMP},",
          "update_date = #{updateDate,jdbcType=TIMESTAMP},",
          "create_uid = #{createUid,jdbcType=INTEGER},",
          "update_uid = #{updateUid,jdbcType=INTEGER},",
          "str_desc = #{strDesc,jdbcType=VARCHAR}",
        "where customer_id = #{customerId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MbCustomer record);
    int customerScoreUpdate(Integer customerId);
    List<Map<String, Object>> firstpage(List<Integer> shopids);

}