package com.mincrm.entity.dao;

import com.mincrm.entity.model.MbGoods;
import com.mincrm.entity.model.MbGoodsExample;
import java.util.List;

import org.apache.ibatis.annotations.*;

@Mapper
public interface MbGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_goods
     *
     * @mbg.generated
     */
    long countByExample(MbGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_goods
     *
     * @mbg.generated
     */
    int deleteByExample(MbGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_goods
     *
     * @mbg.generated
     */
    @Delete({
        "delete from mb_goods",
        "where goods_id = #{goodsId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_goods
     *
     * @mbg.generated
     */
    @Insert({
        "insert into mb_goods (goods_name, shop_id, ",
        "category_id, goods_version, ",
        "goods_purchase_price, goods_sale_price, ",
        "active_flag, create_date, ",
        "update_date, create_uid, ",
        "update_uid, str_desc)",
        "values (#{goodsName,jdbcType=VARCHAR}, #{shopId,jdbcType=INTEGER}, ",
        "#{categoryId,jdbcType=INTEGER}, #{goodsVersion,jdbcType=VARCHAR}, ",
        "#{goodsPurchasePrice,jdbcType=DOUBLE}, #{goodsSalePrice,jdbcType=DOUBLE}, ",
        "#{activeFlag,jdbcType=TINYINT}, #{createDate,jdbcType=TIMESTAMP}, ",
        "#{updateDate,jdbcType=TIMESTAMP}, #{createUid,jdbcType=INTEGER}, ",
        "#{updateUid,jdbcType=INTEGER}, #{strDesc,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="goodsId", before=false, resultType=Integer.class)
    int insert(MbGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_goods
     *
     * @mbg.generated
     */
    int insertSelective(MbGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_goods
     *
     * @mbg.generated
     */
    List<MbGoods> selectByExample(MbGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_goods
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "goods_id, goods_name, shop_id, category_id, goods_version, goods_purchase_price, ",
        "goods_sale_price, active_flag, create_date, update_date, create_uid, update_uid, ",
        "str_desc",
        "from mb_goods",
        "where goods_id = #{goodsId,jdbcType=INTEGER}"
    })
    @ResultMap("com.mincrm.entity.dao.MbGoodsMapper.BaseResultMap")
    MbGoods selectByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MbGoods record, @Param("example") MbGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MbGoods record, @Param("example") MbGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MbGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_goods
     *
     * @mbg.generated
     */
    @Update({
        "update mb_goods",
        "set goods_name = #{goodsName,jdbcType=VARCHAR},",
          "shop_id = #{shopId,jdbcType=INTEGER},",
          "category_id = #{categoryId,jdbcType=INTEGER},",
          "goods_version = #{goodsVersion,jdbcType=VARCHAR},",
          "goods_purchase_price = #{goodsPurchasePrice,jdbcType=DOUBLE},",
          "goods_sale_price = #{goodsSalePrice,jdbcType=DOUBLE},",
          "active_flag = #{activeFlag,jdbcType=TINYINT},",
          "create_date = #{createDate,jdbcType=TIMESTAMP},",
          "update_date = #{updateDate,jdbcType=TIMESTAMP},",
          "create_uid = #{createUid,jdbcType=INTEGER},",
          "update_uid = #{updateUid,jdbcType=INTEGER},",
          "str_desc = #{strDesc,jdbcType=VARCHAR}",
        "where goods_id = #{goodsId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MbGoods record);
}