package com.mincrm.entity.dao;

import com.mincrm.entity.model.MbOrderScore;
import com.mincrm.entity.model.MbOrderScoreExample;
import java.util.List;

import org.apache.ibatis.annotations.*;

@Mapper
public interface MbOrderScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_order_score
     *
     * @mbg.generated
     */
    long countByExample(MbOrderScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_order_score
     *
     * @mbg.generated
     */
    int deleteByExample(MbOrderScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_order_score
     *
     * @mbg.generated
     */
    @Delete({
        "delete from mb_order_score",
        "where order_id = #{orderId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_order_score
     *
     * @mbg.generated
     */
    @Insert({
        "insert into mb_order_score (score_type, category_id, ",
        "goods_id, goods_fact_price, ",
        "customer_id, shop_id, ",
        "goods_score, active_flag, ",
        "create_date, update_date, ",
        "create_uid, update_uid, ",
        "str_desc)",
        "values (#{scoreType,jdbcType=TINYINT}, #{categoryId,jdbcType=INTEGER}, ",
        "#{goodsId,jdbcType=INTEGER}, #{goodsFactPrice,jdbcType=DOUBLE}, ",
        "#{customerId,jdbcType=INTEGER}, #{shopId,jdbcType=INTEGER}, ",
        "#{goodsScore,jdbcType=INTEGER}, #{activeFlag,jdbcType=TINYINT}, ",
        "#{createDate,jdbcType=TIMESTAMP}, #{updateDate,jdbcType=TIMESTAMP}, ",
        "#{createUid,jdbcType=INTEGER}, #{updateUid,jdbcType=INTEGER}, ",
        "#{strDesc,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="orderId", before=false, resultType=Integer.class)
    int insert(MbOrderScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_order_score
     *
     * @mbg.generated
     */
    int insertSelective(MbOrderScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_order_score
     *
     * @mbg.generated
     */
    List<MbOrderScore> selectByExample(MbOrderScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_order_score
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "order_id, score_type, category_id, goods_id, goods_fact_price, customer_id, ",
        "shop_id, goods_score, active_flag, create_date, update_date, create_uid, update_uid, ",
        "str_desc",
        "from mb_order_score",
        "where order_id = #{orderId,jdbcType=INTEGER}"
    })
    @ResultMap("com.mincrm.entity.dao.MbOrderScoreMapper.BaseResultMap")
    MbOrderScore selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_order_score
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MbOrderScore record, @Param("example") MbOrderScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_order_score
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MbOrderScore record, @Param("example") MbOrderScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_order_score
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MbOrderScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_order_score
     *
     * @mbg.generated
     */
    @Update({
        "update mb_order_score",
        "set score_type = #{scoreType,jdbcType=TINYINT},",
          "category_id = #{categoryId,jdbcType=INTEGER},",
          "goods_id = #{goodsId,jdbcType=INTEGER},",
          "goods_fact_price = #{goodsFactPrice,jdbcType=DOUBLE},",
          "customer_id = #{customerId,jdbcType=INTEGER},",
          "shop_id = #{shopId,jdbcType=INTEGER},",
          "goods_score = #{goodsScore,jdbcType=INTEGER},",
          "active_flag = #{activeFlag,jdbcType=TINYINT},",
          "create_date = #{createDate,jdbcType=TIMESTAMP},",
          "update_date = #{updateDate,jdbcType=TIMESTAMP},",
          "create_uid = #{createUid,jdbcType=INTEGER},",
          "update_uid = #{updateUid,jdbcType=INTEGER},",
          "str_desc = #{strDesc,jdbcType=VARCHAR}",
        "where order_id = #{orderId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MbOrderScore record);
}