package com.mincrm.entity.dao;

import com.mincrm.entity.model.MinCategoryTemplate;
import com.mincrm.entity.model.MinCategoryTemplateExample;
import java.util.List;

import org.apache.ibatis.annotations.*;

@Mapper
public interface MinCategoryTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_category_template
     *
     * @mbg.generated
     */
    long countByExample(MinCategoryTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_category_template
     *
     * @mbg.generated
     */
    int deleteByExample(MinCategoryTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_category_template
     *
     * @mbg.generated
     */
    @Delete({
        "delete from min_category_template",
        "where category_id = #{categoryId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_category_template
     *
     * @mbg.generated
     */
    @Insert({
        "insert into min_category_template (category_type, category_type_name, ",
        "min_category, active_flag, ",
        "create_date, update_date, ",
        "create_uid, update_uid)",
        "values (#{categoryType,jdbcType=TINYINT}, #{categoryTypeName,jdbcType=VARCHAR}, ",
        "#{minCategory,jdbcType=VARCHAR}, #{activeFlag,jdbcType=TINYINT}, ",
        "#{createDate,jdbcType=TIMESTAMP}, #{updateDate,jdbcType=TIMESTAMP}, ",
        "#{createUid,jdbcType=INTEGER}, #{updateUid,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="categoryId", before=false, resultType=Integer.class)
    int insert(MinCategoryTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_category_template
     *
     * @mbg.generated
     */
    int insertSelective(MinCategoryTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_category_template
     *
     * @mbg.generated
     */
    List<MinCategoryTemplate> selectByExample(MinCategoryTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_category_template
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "category_id, category_type, category_type_name, min_category, active_flag, create_date, ",
        "update_date, create_uid, update_uid",
        "from min_category_template",
        "where category_id = #{categoryId,jdbcType=INTEGER}"
    })
    @ResultMap("com.mincrm.entity.dao.MinCategoryTemplateMapper.BaseResultMap")
    MinCategoryTemplate selectByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_category_template
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MinCategoryTemplate record, @Param("example") MinCategoryTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_category_template
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MinCategoryTemplate record, @Param("example") MinCategoryTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_category_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MinCategoryTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_category_template
     *
     * @mbg.generated
     */
    @Update({
        "update min_category_template",
        "set category_type = #{categoryType,jdbcType=TINYINT},",
          "category_type_name = #{categoryTypeName,jdbcType=VARCHAR},",
          "min_category = #{minCategory,jdbcType=VARCHAR},",
          "active_flag = #{activeFlag,jdbcType=TINYINT},",
          "create_date = #{createDate,jdbcType=TIMESTAMP},",
          "update_date = #{updateDate,jdbcType=TIMESTAMP},",
          "create_uid = #{createUid,jdbcType=INTEGER},",
          "update_uid = #{updateUid,jdbcType=INTEGER}",
        "where category_id = #{categoryId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MinCategoryTemplate record);
}