package com.mincrm.entity.dao;

import com.mincrm.entity.model.MinShop;
import com.mincrm.entity.model.MinShopExample;
import java.util.List;

import org.apache.ibatis.annotations.*;

@Mapper
public interface MinShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_shop
     *
     * @mbg.generated
     */
    long countByExample(MinShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_shop
     *
     * @mbg.generated
     */
    int deleteByExample(MinShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_shop
     *
     * @mbg.generated
     */
    @Delete({
        "delete from min_shop",
        "where shop_id = #{shopId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer shopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_shop
     *
     * @mbg.generated
     */
    @Insert({
        "insert into min_shop (shop_type, shop_name, ",
        "shop_country, shop_province, ",
        "shop_city, shop_area, ",
        "shop_address, active_flag, ",
        "create_date, update_date, ",
        "create_uid, update_uid, ",
        "str_desc)",
        "values (#{shopType,jdbcType=TINYINT}, #{shopName,jdbcType=VARCHAR}, ",
        "#{shopCountry,jdbcType=VARCHAR}, #{shopProvince,jdbcType=VARCHAR}, ",
        "#{shopCity,jdbcType=VARCHAR}, #{shopArea,jdbcType=VARCHAR}, ",
        "#{shopAddress,jdbcType=VARCHAR}, #{activeFlag,jdbcType=TINYINT}, ",
        "#{createDate,jdbcType=TIMESTAMP}, #{updateDate,jdbcType=TIMESTAMP}, ",
        "#{createUid,jdbcType=INTEGER}, #{updateUid,jdbcType=INTEGER}, ",
        "#{strDesc,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="shopId", before=false, resultType=Integer.class)
    int insert(MinShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_shop
     *
     * @mbg.generated
     */
    int insertSelective(MinShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_shop
     *
     * @mbg.generated
     */
    List<MinShop> selectByExample(MinShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_shop
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "shop_id, shop_type, shop_name, shop_country, shop_province, shop_city, shop_area, ",
        "shop_address, active_flag, create_date, update_date, create_uid, update_uid, ",
        "str_desc",
        "from min_shop",
        "where shop_id = #{shopId,jdbcType=INTEGER}"
    })
    @ResultMap("com.mincrm.entity.dao.MinShopMapper.BaseResultMap")
    MinShop selectByPrimaryKey(Integer shopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_shop
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MinShop record, @Param("example") MinShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_shop
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MinShop record, @Param("example") MinShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_shop
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MinShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_shop
     *
     * @mbg.generated
     */
    @Update({
        "update min_shop",
        "set shop_type = #{shopType,jdbcType=TINYINT},",
          "shop_name = #{shopName,jdbcType=VARCHAR},",
          "shop_country = #{shopCountry,jdbcType=VARCHAR},",
          "shop_province = #{shopProvince,jdbcType=VARCHAR},",
          "shop_city = #{shopCity,jdbcType=VARCHAR},",
          "shop_area = #{shopArea,jdbcType=VARCHAR},",
          "shop_address = #{shopAddress,jdbcType=VARCHAR},",
          "active_flag = #{activeFlag,jdbcType=TINYINT},",
          "create_date = #{createDate,jdbcType=TIMESTAMP},",
          "update_date = #{updateDate,jdbcType=TIMESTAMP},",
          "create_uid = #{createUid,jdbcType=INTEGER},",
          "update_uid = #{updateUid,jdbcType=INTEGER},",
          "str_desc = #{strDesc,jdbcType=VARCHAR}",
        "where shop_id = #{shopId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MinShop record);
}