package com.mincrm.entity.dao;

import com.mincrm.entity.model.VMbOrderScoreExchange;
import com.mincrm.entity.model.VMbOrderScoreExchangeExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface VMbOrderScoreExchangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_mb_order_score_exchange
     *
     * @mbg.generated
     */
    long countByExample(VMbOrderScoreExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_mb_order_score_exchange
     *
     * @mbg.generated
     */
    int deleteByExample(VMbOrderScoreExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_mb_order_score_exchange
     *
     * @mbg.generated
     */
    @Insert({
        "insert into v_mb_order_score_exchange (order_id, customer_id, ",
        "customer_name, customer_tel, ",
        "goods_fact_price, create_date, ",
        "create_uid, category_id, ",
        "goods_id, goods_name, ",
        "goods_version, score_type, ",
        "active_flag, shop_id, ",
        "goods_score, update_date, ",
        "update_uid, goods_purchase_price, ",
        "goods_sale_price, str_desc, ",
        "customer_score)",
        "values (#{orderId,jdbcType=INTEGER}, #{customerId,jdbcType=INTEGER}, ",
        "#{customerName,jdbcType=VARCHAR}, #{customerTel,jdbcType=VARCHAR}, ",
        "#{goodsFactPrice,jdbcType=DOUBLE}, #{createDate,jdbcType=TIMESTAMP}, ",
        "#{createUid,jdbcType=INTEGER}, #{categoryId,jdbcType=INTEGER}, ",
        "#{goodsId,jdbcType=INTEGER}, #{goodsName,jdbcType=VARCHAR}, ",
        "#{goodsVersion,jdbcType=VARCHAR}, #{scoreType,jdbcType=TINYINT}, ",
        "#{activeFlag,jdbcType=TINYINT}, #{shopId,jdbcType=INTEGER}, ",
        "#{goodsScore,jdbcType=INTEGER}, #{updateDate,jdbcType=TIMESTAMP}, ",
        "#{updateUid,jdbcType=INTEGER}, #{goodsPurchasePrice,jdbcType=DOUBLE}, ",
        "#{goodsSalePrice,jdbcType=DOUBLE}, #{strDesc,jdbcType=VARCHAR}, ",
        "#{customerScore,jdbcType=INTEGER})"
    })
    int insert(VMbOrderScoreExchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_mb_order_score_exchange
     *
     * @mbg.generated
     */
    int insertSelective(VMbOrderScoreExchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_mb_order_score_exchange
     *
     * @mbg.generated
     */
    List<VMbOrderScoreExchange> selectByExample(VMbOrderScoreExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_mb_order_score_exchange
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VMbOrderScoreExchange record, @Param("example") VMbOrderScoreExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_mb_order_score_exchange
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VMbOrderScoreExchange record, @Param("example") VMbOrderScoreExchangeExample example);
}