package com.mincrm.entity.dao;

import com.mincrm.entity.model.VShopAccountRole;
import com.mincrm.entity.model.VShopAccountRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface VShopAccountRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_shop_account_role
     *
     * @mbg.generated
     */
    long countByExample(VShopAccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_shop_account_role
     *
     * @mbg.generated
     */
    int deleteByExample(VShopAccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_shop_account_role
     *
     * @mbg.generated
     */
    @Insert({
        "insert into v_shop_account_role (shop_id, shop_name, ",
        "shop_country, shop_province, ",
        "shop_city, shop_area, ",
        "shop_address, active_flag, ",
        "create_date, create_uid, ",
        "str_desc, role_id, ",
        "uid, role_type)",
        "values (#{shopId,jdbcType=INTEGER}, #{shopName,jdbcType=VARCHAR}, ",
        "#{shopCountry,jdbcType=VARCHAR}, #{shopProvince,jdbcType=VARCHAR}, ",
        "#{shopCity,jdbcType=VARCHAR}, #{shopArea,jdbcType=VARCHAR}, ",
        "#{shopAddress,jdbcType=VARCHAR}, #{activeFlag,jdbcType=TINYINT}, ",
        "#{createDate,jdbcType=TIMESTAMP}, #{createUid,jdbcType=INTEGER}, ",
        "#{strDesc,jdbcType=VARCHAR}, #{roleId,jdbcType=INTEGER}, ",
        "#{uid,jdbcType=INTEGER}, #{roleType,jdbcType=TINYINT})"
    })
    int insert(VShopAccountRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_shop_account_role
     *
     * @mbg.generated
     */
    int insertSelective(VShopAccountRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_shop_account_role
     *
     * @mbg.generated
     */
    List<VShopAccountRole> selectByExample(VShopAccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_shop_account_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VShopAccountRole record, @Param("example") VShopAccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_shop_account_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VShopAccountRole record, @Param("example") VShopAccountRoleExample example);
}